// This source code was generated by ClangCaster

namespace NWindowsKits
{
    // C:/Program Files (x86)/Windows Kits/10/Include/10.0.18362.0/um/d3d11.h:10378
    public enum D3D11_VIDEO_PROCESSOR_NOMINAL_RANGE
    {
        _UNDEFINED = 0x0,
        _16_235 = 0x1,
        _0_255 = 0x2,
    }
}
