// This source code was generated by ClangCaster

namespace NWindowsKits
{
    // C:/Program Files (x86)/Windows Kits/10/Include/10.0.18362.0/um/d3d11.h:5850
    public enum D3D11_TEXTURE_ADDRESS_MODE // 1
    {
        _WRAP = 0x1,
        _MIRROR = 0x2,
        _CLAMP = 0x3,
        _BORDER = 0x4,
        _MIRROR_ONCE = 0x5,
    }
}
