// This source code was generated by ClangCaster

namespace NWindowsKits
{
    // C:/Program Files (x86)/Windows Kits/10/Include/10.0.18362.0/um/d3d11.h:9922
    public enum D3D11_VIDEO_PROCESSOR_FORMAT_SUPPORT // 1
    {
        _INPUT = 0x1,
        _OUTPUT = 0x2,
    }
}
