// This source code was generated by ClangCaster

namespace NWindowsKits
{
    // C:/Program Files (x86)/Windows Kits/10/Include/10.0.18362.0/um/d3d11.h:1792
    public enum D3D11_COLOR_WRITE_ENABLE
    {
        _RED = 0x1,
        _GREEN = 0x2,
        _BLUE = 0x4,
        _ALPHA = 0x8,
        _ALL = 0xf,
    }
}
