// This source code was generated by ClangCaster

namespace NWindowsKits
{
    // C:/Program Files (x86)/Windows Kits/10/Include/10.0.18362.0/um/d3d11.h:3157
    public enum D3D11_TEXTURECUBE_FACE // 1
    {
        _POSITIVE_X = 0x0,
        _NEGATIVE_X = 0x1,
        _POSITIVE_Y = 0x2,
        _NEGATIVE_Y = 0x3,
        _POSITIVE_Z = 0x4,
        _NEGATIVE_Z = 0x5,
    }
}
