// This source code was generated by ClangCaster

namespace NWindowsKits
{
    // C:/Program Files (x86)/Windows Kits/10/Include/10.0.18362.0/um/d3d11.h:1159
    public enum D3D11_RESOURCE_DIMENSION
    {
        _UNKNOWN = 0x0,
        _BUFFER = 0x1,
        _TEXTURE1D = 0x2,
        _TEXTURE2D = 0x3,
        _TEXTURE3D = 0x4,
    }
}
