// This source code was generated by ClangCaster

namespace NWindowsKits
{
    // C:/Program Files (x86)/Windows Kits/10/Include/10.0.18362.0/um/d3d11.h:14390
    public enum D3D11_CREATE_DEVICE_FLAG // 1
    {
        _SINGLETHREADED = 0x1,
        _DEBUG = 0x2,
        _SWITCH_TO_REF = 0x4,
        _PREVENT_INTERNAL_THREADING_OPTIMIZATIONS = 0x8,
        _BGRA_SUPPORT = 0x20,
        _DEBUGGABLE = 0x40,
        _PREVENT_ALTERING_LAYER_SETTINGS_FROM_REGISTRY = 0x80,
        _DISABLE_GPU_TIMEOUT = 0x100,
        _VIDEO_SUPPORT = 0x800,
    }
}
