// This source code was generated by ClangCaster
using System;
using System.Runtime.InteropServices;

namespace NWindowsKits
{
    // C:/Program Files (x86)/Windows Kits/10/Include/10.0.18362.0/um/WinUser.h:4670
    [StructLayout(LayoutKind.Sequential, CharSet = CharSet.Unicode)]
    public struct FLASHWINFO // 2
    {
        public uint cbSize;
        public HWND hwnd;
        public uint dwFlags;
        public uint uCount;
        public uint dwTimeout;
    }
}
