// This source code was generated by ClangCaster
using System;
using System.Runtime.InteropServices;

namespace NWindowsKits
{
    // C:/Program Files (x86)/Windows Kits/10/Include/10.0.18362.0/um/WinUser.h:7738
    [StructLayout(LayoutKind.Sequential, CharSet = CharSet.Unicode)]
    public struct MENUINFO
    {

        public uint cbSize;
        public uint fMask;
        public uint dwStyle;
        public uint cyMax;
        public HBRUSH hbrBack;
        public uint dwContextHelpID;
        public ulong dwMenuData;
    }
}
