// This source code was generated by ClangCaster
using System;
using System.Runtime.InteropServices;

namespace NWindowsKits
{
    // C:/Program Files (x86)/Windows Kits/10/Include/10.0.18362.0/um/winuser.h:1879
    [StructLayout(LayoutKind.Sequential)]
    public struct MSG // 4
    {
        public HWND hwnd;
        public uint message;
        public ulong wParam;
        public long lParam;
        public uint time;
        public POINT pt;
    }
}
