// This source code was generated by ClangCaster
using System;
using System.Runtime.InteropServices;

namespace NWindowsKits
{
    // C:/Program Files (x86)/Windows Kits/10/Include/10.0.18362.0/um/WinUser.h:15314
    [StructLayout(LayoutKind.Sequential, CharSet = CharSet.Unicode)]
    public struct POINTER_DEVICE_PROPERTY
    {

        public int logicalMin;
        public int logicalMax;
        public int physicalMin;
        public int physicalMax;
        public uint unit;
        public uint unitExponent;
        public ushort usagePageId;
        public ushort usageId;
    }
}
