// This source code was generated by ClangCaster
using System;
using System.Runtime.InteropServices;

namespace NWindowsKits
{
    // C:/Program Files (x86)/Windows Kits/10/Include/10.0.18362.0/um/winuser.h:1337
    [StructLayout(LayoutKind.Sequential, CharSet = CharSet.Unicode)]
    public struct tagMOUSEMOVEPOINT // 3
    {
        public int x;
        public int y;
        public uint time;
        public ulong dwExtraInfo;
    }
}
