// This source code was generated by ClangCaster
using System;
using System.Runtime.InteropServices;

namespace NWindowsKits
{
    // C:/Program Files (x86)/Windows Kits/10/Include/10.0.18362.0/um/WinUser.h:12510
    [StructLayout(LayoutKind.Sequential, CharSet = CharSet.Unicode)]
    public struct TOUCHPREDICTIONPARAMETERS
    {

        public uint cbSize;
        public uint dwLatency;
        public uint dwSampleTime;
        public uint bUseHWTimeStamp;
    }
}
