// This source code was generated by ClangCaster
using System;
using System.Runtime.InteropServices;

namespace NWindowsKits
{
    // C:/Program Files (x86)/Windows Kits/10/Include/10.0.18362.0/um/WinUser.h:6452
    [StructLayout(LayoutKind.Sequential, CharSet = CharSet.Unicode)]
    public struct USAGE_PROPERTIES
    {

        public ushort level;
        public ushort page;
        public ushort usage;
        public int logicalMinimum;
        public int logicalMaximum;
        public ushort unit;
        public ushort exponent;
        public byte count;
        public int physicalMinimum;
        public int physicalMaximum;
    }
}
