// This source code was generated by ClangCaster

namespace NWindowsKits
{
    // C:/Program Files (x86)/Windows Kits/10/Include/10.0.18362.0/um/OAIdl.h:4248
    public enum CHANGEKIND
    {
        _ADDMEMBER = 0x0,
        _DELETEMEMBER = 0x1,
        _SETNAMES = 0x2,
        _SETDOCUMENTATION = 0x3,
        _GENERAL = 0x4,
        _INVALIDATE = 0x5,
        _CHANGEFAILED = 0x6,
        _MAX = 0x7,
    }
}
