// This source code was generated by ClangCaster

namespace NWindowsKits
{
    // C:/Program Files (x86)/Windows Kits/10/Include/10.0.18362.0/um/OAIdl.h:852
    public enum VARKIND
    {
        _PERINSTANCE = 0x0,
        _STATIC = 0x1,
        _CONST = 0x2,
        _DISPATCH = 0x3,
    }
}
