// This source code was generated by ClangCaster
using System;
using System.Runtime.InteropServices;

namespace NWindowsKits
{
    // C:/Program Files (x86)/Windows Kits/10/Include/10.0.18362.0/um/d3d10.h:1505
    public class ID3D10Resource : ID3D10DeviceChild // 1
    {
        static Guid s_uuid = new Guid("9b7e4c01-342c-4106-a19f-4f2704f689f0");
        public static new ref Guid IID => ref s_uuid;
        public override ref Guid GetIID() { return ref s_uuid; }

        public void GetType(ref D3D10_RESOURCE_DIMENSION rType)
        {
            if(m_GetTypeFunc==null){
                var fp = GetFunctionPointer(7);
                m_GetTypeFunc = (GetTypeFunc)Marshal.GetDelegateForFunctionPointer(fp, typeof(GetTypeFunc));
            } 
             m_GetTypeFunc(m_ptr, ref rType);
        }
        delegate void GetTypeFunc(IntPtr self, ref D3D10_RESOURCE_DIMENSION rType);
        GetTypeFunc m_GetTypeFunc;

        public void SetEvictionPriority(uint EvictionPriority)
        {
            if(m_SetEvictionPriorityFunc==null){
                var fp = GetFunctionPointer(8);
                m_SetEvictionPriorityFunc = (SetEvictionPriorityFunc)Marshal.GetDelegateForFunctionPointer(fp, typeof(SetEvictionPriorityFunc));
            } 
             m_SetEvictionPriorityFunc(m_ptr, EvictionPriority);
        }
        delegate void SetEvictionPriorityFunc(IntPtr self, uint EvictionPriority);
        SetEvictionPriorityFunc m_SetEvictionPriorityFunc;

        public uint GetEvictionPriority()
        {
            if(m_GetEvictionPriorityFunc==null){
                var fp = GetFunctionPointer(9);
                m_GetEvictionPriorityFunc = (GetEvictionPriorityFunc)Marshal.GetDelegateForFunctionPointer(fp, typeof(GetEvictionPriorityFunc));
            } 
            return  m_GetEvictionPriorityFunc(m_ptr);
        }
        delegate uint GetEvictionPriorityFunc(IntPtr self);
        GetEvictionPriorityFunc m_GetEvictionPriorityFunc;

    }
}
