// This source code was generated by ClangCaster
using System;
using System.Runtime.InteropServices;

namespace NWindowsKits
{
    // C:/Program Files (x86)/Windows Kits/10/Include/10.0.18362.0/um/d3d10.h:827
    public class ID3D10DeviceChild : IUnknown
    {
        static Guid s_uuid = new Guid("9b7e4c00-342c-4106-a19f-4f2704f689f0");
        public static new ref Guid IID => ref s_uuid;
        public override ref Guid GetIID() { return ref s_uuid; }

        public void GetDevice(ref IntPtr ppDevice)
        {
            if(m_GetDeviceFunc==null){
                var fp = GetFunctionPointer(3);
                m_GetDeviceFunc = (GetDeviceFunc)Marshal.GetDelegateForFunctionPointer(fp, typeof(GetDeviceFunc));
            } 
             m_GetDeviceFunc(m_ptr, ref ppDevice);
        }
        delegate void GetDeviceFunc(IntPtr self, ref IntPtr ppDevice);
        GetDeviceFunc m_GetDeviceFunc;

        public int GetPrivateData(ref GUID guid, ref uint pDataSize, IntPtr pData)
        {
            if(m_GetPrivateDataFunc==null){
                var fp = GetFunctionPointer(4);
                m_GetPrivateDataFunc = (GetPrivateDataFunc)Marshal.GetDelegateForFunctionPointer(fp, typeof(GetPrivateDataFunc));
            } 
            return  m_GetPrivateDataFunc(m_ptr, ref guid, ref pDataSize, pData);
        }
        delegate int GetPrivateDataFunc(IntPtr self, ref GUID guid, ref uint pDataSize, IntPtr pData);
        GetPrivateDataFunc m_GetPrivateDataFunc;

        public int SetPrivateData(ref GUID guid, uint DataSize, IntPtr pData)
        {
            if(m_SetPrivateDataFunc==null){
                var fp = GetFunctionPointer(5);
                m_SetPrivateDataFunc = (SetPrivateDataFunc)Marshal.GetDelegateForFunctionPointer(fp, typeof(SetPrivateDataFunc));
            } 
            return  m_SetPrivateDataFunc(m_ptr, ref guid, DataSize, pData);
        }
        delegate int SetPrivateDataFunc(IntPtr self, ref GUID guid, uint DataSize, IntPtr pData);
        SetPrivateDataFunc m_SetPrivateDataFunc;

        public int SetPrivateDataInterface(ref GUID guid, IntPtr pData)
        {
            if(m_SetPrivateDataInterfaceFunc==null){
                var fp = GetFunctionPointer(6);
                m_SetPrivateDataInterfaceFunc = (SetPrivateDataInterfaceFunc)Marshal.GetDelegateForFunctionPointer(fp, typeof(SetPrivateDataInterfaceFunc));
            } 
            return  m_SetPrivateDataInterfaceFunc(m_ptr, ref guid, pData);
        }
        delegate int SetPrivateDataInterfaceFunc(IntPtr self, ref GUID guid, IntPtr pData);
        SetPrivateDataInterfaceFunc m_SetPrivateDataInterfaceFunc;

    }
}
