// This source code was generated by ClangCaster
using System;
using System.Runtime.InteropServices;

namespace NWindowsKits
{
    // C:/Program Files (x86)/Windows Kits/10/Include/10.0.18362.0/um/d3d10.h:3595
    public class ID3D10PixelShader : ID3D10DeviceChild // 1
    {
        static Guid s_uuid = new Guid("4968b601-9d00-4cde-8346-8e7f675819b6");
        public static new ref Guid IID => ref s_uuid;
        public override ref Guid GetIID() { return ref s_uuid; }

    }
}
