// This source code was generated by ClangCaster

namespace NWindowsKits
{
    // C:/Program Files (x86)/Windows Kits/10/Include/10.0.18362.0/um/winuser.h:5331
    public enum DIALOG_DPI_CHANGE_BEHAVIORS // 1
    {
        _DEFAULT = 0x0,
        _DISABLE_ALL = 0x1,
        _DISABLE_RESIZE = 0x2,
        _DISABLE_CONTROL_RELAYOUT = 0x4,
    }
}
