// This source code was generated by ClangCaster

namespace NWindowsKits
{
    // C:/Program Files (x86)/Windows Kits/10/Include/10.0.18362.0/um/WinUser.h:15830
    public enum ORIENTATION_PREFERENCE
    {
        _NONE = 0x0,
        _LANDSCAPE = 0x1,
        _PORTRAIT = 0x2,
        _LANDSCAPE_FLIPPED = 0x4,
        _PORTRAIT_FLIPPED = 0x8,
    }
}
