// This source code was generated by ClangCaster

namespace NWindowsKits
{
    // C:/Program Files (x86)/Windows Kits/10/Include/10.0.18362.0/um/WinUser.h:15325
    public enum POINTER_DEVICE_CURSOR_TYPE // 1
    {
        _UNKNOWN = 0x0,
        _TIP = 0x1,
        _ERASER = 0x2,
        _MAX = unchecked((int)0xffffffff),
    }
}
