// This source code was generated by ClangCaster

namespace NWindowsKits
{
    // C:/Program Files (x86)/Windows Kits/10/Include/10.0.18362.0/um/WinUser.h:6257
    public enum tagPOINTER_INPUT_TYPE
    {
        _POINTER = 0x1,
        _TOUCH = 0x2,
        _PEN = 0x3,
        _MOUSE = 0x4,
        _TOUCHPAD = 0x5,
    }
}
