// This source code was generated by ClangCaster

namespace NWindowsKits
{
    // C:/Program Files (x86)/Windows Kits/10/Include/10.0.18362.0/um/d3d10sdklayers.h:343
    public enum D3D10_MESSAGE_CATEGORY
    {
        _APPLICATION_DEFINED = 0x0,
        _MISCELLANEOUS = 0x1,
        _INITIALIZATION = 0x2,
        _CLEANUP = 0x3,
        _COMPILATION = 0x4,
        _STATE_CREATION = 0x5,
        _STATE_SETTING = 0x6,
        _STATE_GETTING = 0x7,
        _RESOURCE_MANIPULATION = 0x8,
        _EXECUTION = 0x9,
        _SHADER = 0xa,
    }
}
