// This source code was generated by ClangCaster

namespace NWindowsKits
{
    // C:/Program Files (x86)/Windows Kits/10/Include/10.0.18362.0/um/objidlbase.h:7479
    public enum CO_MARSHALING_CONTEXT_ATTRIBUTES
    {
        _SOURCE_IS_APP_CONTAINER = 0x0,
        _CONTEXT_ATTRIBUTE_RESERVED_1 = unchecked((int)0x80000000),
        _CONTEXT_ATTRIBUTE_RESERVED_2 = unchecked((int)0x80000001),
        _CONTEXT_ATTRIBUTE_RESERVED_3 = unchecked((int)0x80000002),
        _CONTEXT_ATTRIBUTE_RESERVED_4 = unchecked((int)0x80000003),
        _CONTEXT_ATTRIBUTE_RESERVED_5 = unchecked((int)0x80000004),
        _CONTEXT_ATTRIBUTE_RESERVED_6 = unchecked((int)0x80000005),
        _CONTEXT_ATTRIBUTE_RESERVED_7 = unchecked((int)0x80000006),
        _CONTEXT_ATTRIBUTE_RESERVED_8 = unchecked((int)0x80000007),
        _CONTEXT_ATTRIBUTE_RESERVED_9 = unchecked((int)0x80000008),
        _CONTEXT_ATTRIBUTE_RESERVED_10 = unchecked((int)0x80000009),
        _CONTEXT_ATTRIBUTE_RESERVED_11 = unchecked((int)0x8000000a),
        _CONTEXT_ATTRIBUTE_RESERVED_12 = unchecked((int)0x8000000b),
        _CONTEXT_ATTRIBUTE_RESERVED_13 = unchecked((int)0x8000000c),
        _CONTEXT_ATTRIBUTE_RESERVED_14 = unchecked((int)0x8000000d),
        _CONTEXT_ATTRIBUTE_RESERVED_15 = unchecked((int)0x8000000e),
        _CONTEXT_ATTRIBUTE_RESERVED_16 = unchecked((int)0x8000000f),
        _CONTEXT_ATTRIBUTE_RESERVED_17 = unchecked((int)0x80000010),
    }
}
