// This source code was generated by ClangCaster
using System;
using System.Runtime.InteropServices;

namespace NWindowsKits
{
    // C:/Program Files (x86)/Windows Kits/10/Include/10.0.18362.0/um/d3d10sdklayers.h:926
    public class ID3D10InfoQueue : IUnknown
    {
        static Guid s_uuid = new Guid("1b940b17-2642-4d1f-ab1f-b99bad0c395f");
        public static new ref Guid IID => ref s_uuid;
        public override ref Guid GetIID() { return ref s_uuid; }

        public int SetMessageCountLimit(ulong MessageCountLimit)
        {
            if(m_SetMessageCountLimitFunc==null){
                var fp = GetFunctionPointer(3);
                m_SetMessageCountLimitFunc = (SetMessageCountLimitFunc)Marshal.GetDelegateForFunctionPointer(fp, typeof(SetMessageCountLimitFunc));
            } 
            return  m_SetMessageCountLimitFunc(m_ptr, MessageCountLimit);
        }
        delegate int SetMessageCountLimitFunc(IntPtr self, ulong MessageCountLimit);
        SetMessageCountLimitFunc m_SetMessageCountLimitFunc;

        public void ClearStoredMessages()
        {
            if(m_ClearStoredMessagesFunc==null){
                var fp = GetFunctionPointer(4);
                m_ClearStoredMessagesFunc = (ClearStoredMessagesFunc)Marshal.GetDelegateForFunctionPointer(fp, typeof(ClearStoredMessagesFunc));
            } 
             m_ClearStoredMessagesFunc(m_ptr);
        }
        delegate void ClearStoredMessagesFunc(IntPtr self);
        ClearStoredMessagesFunc m_ClearStoredMessagesFunc;

        public int GetMessageA(ulong MessageIndex, ref D3D10_MESSAGE pMessage, IntPtr pMessageByteLength)
        {
            if(m_GetMessageAFunc==null){
                var fp = GetFunctionPointer(5);
                m_GetMessageAFunc = (GetMessageAFunc)Marshal.GetDelegateForFunctionPointer(fp, typeof(GetMessageAFunc));
            } 
            return  m_GetMessageAFunc(m_ptr, MessageIndex, ref pMessage, pMessageByteLength);
        }
        delegate int GetMessageAFunc(IntPtr self, ulong MessageIndex, ref D3D10_MESSAGE pMessage, IntPtr pMessageByteLength);
        GetMessageAFunc m_GetMessageAFunc;

        public ulong GetNumMessagesAllowedByStorageFilter()
        {
            if(m_GetNumMessagesAllowedByStorageFilterFunc==null){
                var fp = GetFunctionPointer(6);
                m_GetNumMessagesAllowedByStorageFilterFunc = (GetNumMessagesAllowedByStorageFilterFunc)Marshal.GetDelegateForFunctionPointer(fp, typeof(GetNumMessagesAllowedByStorageFilterFunc));
            } 
            return  m_GetNumMessagesAllowedByStorageFilterFunc(m_ptr);
        }
        delegate ulong GetNumMessagesAllowedByStorageFilterFunc(IntPtr self);
        GetNumMessagesAllowedByStorageFilterFunc m_GetNumMessagesAllowedByStorageFilterFunc;

        public ulong GetNumMessagesDeniedByStorageFilter()
        {
            if(m_GetNumMessagesDeniedByStorageFilterFunc==null){
                var fp = GetFunctionPointer(7);
                m_GetNumMessagesDeniedByStorageFilterFunc = (GetNumMessagesDeniedByStorageFilterFunc)Marshal.GetDelegateForFunctionPointer(fp, typeof(GetNumMessagesDeniedByStorageFilterFunc));
            } 
            return  m_GetNumMessagesDeniedByStorageFilterFunc(m_ptr);
        }
        delegate ulong GetNumMessagesDeniedByStorageFilterFunc(IntPtr self);
        GetNumMessagesDeniedByStorageFilterFunc m_GetNumMessagesDeniedByStorageFilterFunc;

        public ulong GetNumStoredMessages()
        {
            if(m_GetNumStoredMessagesFunc==null){
                var fp = GetFunctionPointer(8);
                m_GetNumStoredMessagesFunc = (GetNumStoredMessagesFunc)Marshal.GetDelegateForFunctionPointer(fp, typeof(GetNumStoredMessagesFunc));
            } 
            return  m_GetNumStoredMessagesFunc(m_ptr);
        }
        delegate ulong GetNumStoredMessagesFunc(IntPtr self);
        GetNumStoredMessagesFunc m_GetNumStoredMessagesFunc;

        public ulong GetNumStoredMessagesAllowedByRetrievalFilter()
        {
            if(m_GetNumStoredMessagesAllowedByRetrievalFilterFunc==null){
                var fp = GetFunctionPointer(9);
                m_GetNumStoredMessagesAllowedByRetrievalFilterFunc = (GetNumStoredMessagesAllowedByRetrievalFilterFunc)Marshal.GetDelegateForFunctionPointer(fp, typeof(GetNumStoredMessagesAllowedByRetrievalFilterFunc));
            } 
            return  m_GetNumStoredMessagesAllowedByRetrievalFilterFunc(m_ptr);
        }
        delegate ulong GetNumStoredMessagesAllowedByRetrievalFilterFunc(IntPtr self);
        GetNumStoredMessagesAllowedByRetrievalFilterFunc m_GetNumStoredMessagesAllowedByRetrievalFilterFunc;

        public ulong GetNumMessagesDiscardedByMessageCountLimit()
        {
            if(m_GetNumMessagesDiscardedByMessageCountLimitFunc==null){
                var fp = GetFunctionPointer(10);
                m_GetNumMessagesDiscardedByMessageCountLimitFunc = (GetNumMessagesDiscardedByMessageCountLimitFunc)Marshal.GetDelegateForFunctionPointer(fp, typeof(GetNumMessagesDiscardedByMessageCountLimitFunc));
            } 
            return  m_GetNumMessagesDiscardedByMessageCountLimitFunc(m_ptr);
        }
        delegate ulong GetNumMessagesDiscardedByMessageCountLimitFunc(IntPtr self);
        GetNumMessagesDiscardedByMessageCountLimitFunc m_GetNumMessagesDiscardedByMessageCountLimitFunc;

        public ulong GetMessageCountLimit()
        {
            if(m_GetMessageCountLimitFunc==null){
                var fp = GetFunctionPointer(11);
                m_GetMessageCountLimitFunc = (GetMessageCountLimitFunc)Marshal.GetDelegateForFunctionPointer(fp, typeof(GetMessageCountLimitFunc));
            } 
            return  m_GetMessageCountLimitFunc(m_ptr);
        }
        delegate ulong GetMessageCountLimitFunc(IntPtr self);
        GetMessageCountLimitFunc m_GetMessageCountLimitFunc;

        public int AddStorageFilterEntries(ref D3D10_INFO_QUEUE_FILTER pFilter)
        {
            if(m_AddStorageFilterEntriesFunc==null){
                var fp = GetFunctionPointer(12);
                m_AddStorageFilterEntriesFunc = (AddStorageFilterEntriesFunc)Marshal.GetDelegateForFunctionPointer(fp, typeof(AddStorageFilterEntriesFunc));
            } 
            return  m_AddStorageFilterEntriesFunc(m_ptr, ref pFilter);
        }
        delegate int AddStorageFilterEntriesFunc(IntPtr self, ref D3D10_INFO_QUEUE_FILTER pFilter);
        AddStorageFilterEntriesFunc m_AddStorageFilterEntriesFunc;

        public int GetStorageFilter(ref D3D10_INFO_QUEUE_FILTER pFilter, IntPtr pFilterByteLength)
        {
            if(m_GetStorageFilterFunc==null){
                var fp = GetFunctionPointer(13);
                m_GetStorageFilterFunc = (GetStorageFilterFunc)Marshal.GetDelegateForFunctionPointer(fp, typeof(GetStorageFilterFunc));
            } 
            return  m_GetStorageFilterFunc(m_ptr, ref pFilter, pFilterByteLength);
        }
        delegate int GetStorageFilterFunc(IntPtr self, ref D3D10_INFO_QUEUE_FILTER pFilter, IntPtr pFilterByteLength);
        GetStorageFilterFunc m_GetStorageFilterFunc;

        public void ClearStorageFilter()
        {
            if(m_ClearStorageFilterFunc==null){
                var fp = GetFunctionPointer(14);
                m_ClearStorageFilterFunc = (ClearStorageFilterFunc)Marshal.GetDelegateForFunctionPointer(fp, typeof(ClearStorageFilterFunc));
            } 
             m_ClearStorageFilterFunc(m_ptr);
        }
        delegate void ClearStorageFilterFunc(IntPtr self);
        ClearStorageFilterFunc m_ClearStorageFilterFunc;

        public int PushEmptyStorageFilter()
        {
            if(m_PushEmptyStorageFilterFunc==null){
                var fp = GetFunctionPointer(15);
                m_PushEmptyStorageFilterFunc = (PushEmptyStorageFilterFunc)Marshal.GetDelegateForFunctionPointer(fp, typeof(PushEmptyStorageFilterFunc));
            } 
            return  m_PushEmptyStorageFilterFunc(m_ptr);
        }
        delegate int PushEmptyStorageFilterFunc(IntPtr self);
        PushEmptyStorageFilterFunc m_PushEmptyStorageFilterFunc;

        public int PushCopyOfStorageFilter()
        {
            if(m_PushCopyOfStorageFilterFunc==null){
                var fp = GetFunctionPointer(16);
                m_PushCopyOfStorageFilterFunc = (PushCopyOfStorageFilterFunc)Marshal.GetDelegateForFunctionPointer(fp, typeof(PushCopyOfStorageFilterFunc));
            } 
            return  m_PushCopyOfStorageFilterFunc(m_ptr);
        }
        delegate int PushCopyOfStorageFilterFunc(IntPtr self);
        PushCopyOfStorageFilterFunc m_PushCopyOfStorageFilterFunc;

        public int PushStorageFilter(ref D3D10_INFO_QUEUE_FILTER pFilter)
        {
            if(m_PushStorageFilterFunc==null){
                var fp = GetFunctionPointer(17);
                m_PushStorageFilterFunc = (PushStorageFilterFunc)Marshal.GetDelegateForFunctionPointer(fp, typeof(PushStorageFilterFunc));
            } 
            return  m_PushStorageFilterFunc(m_ptr, ref pFilter);
        }
        delegate int PushStorageFilterFunc(IntPtr self, ref D3D10_INFO_QUEUE_FILTER pFilter);
        PushStorageFilterFunc m_PushStorageFilterFunc;

        public void PopStorageFilter()
        {
            if(m_PopStorageFilterFunc==null){
                var fp = GetFunctionPointer(18);
                m_PopStorageFilterFunc = (PopStorageFilterFunc)Marshal.GetDelegateForFunctionPointer(fp, typeof(PopStorageFilterFunc));
            } 
             m_PopStorageFilterFunc(m_ptr);
        }
        delegate void PopStorageFilterFunc(IntPtr self);
        PopStorageFilterFunc m_PopStorageFilterFunc;

        public uint GetStorageFilterStackSize()
        {
            if(m_GetStorageFilterStackSizeFunc==null){
                var fp = GetFunctionPointer(19);
                m_GetStorageFilterStackSizeFunc = (GetStorageFilterStackSizeFunc)Marshal.GetDelegateForFunctionPointer(fp, typeof(GetStorageFilterStackSizeFunc));
            } 
            return  m_GetStorageFilterStackSizeFunc(m_ptr);
        }
        delegate uint GetStorageFilterStackSizeFunc(IntPtr self);
        GetStorageFilterStackSizeFunc m_GetStorageFilterStackSizeFunc;

        public int AddRetrievalFilterEntries(ref D3D10_INFO_QUEUE_FILTER pFilter)
        {
            if(m_AddRetrievalFilterEntriesFunc==null){
                var fp = GetFunctionPointer(20);
                m_AddRetrievalFilterEntriesFunc = (AddRetrievalFilterEntriesFunc)Marshal.GetDelegateForFunctionPointer(fp, typeof(AddRetrievalFilterEntriesFunc));
            } 
            return  m_AddRetrievalFilterEntriesFunc(m_ptr, ref pFilter);
        }
        delegate int AddRetrievalFilterEntriesFunc(IntPtr self, ref D3D10_INFO_QUEUE_FILTER pFilter);
        AddRetrievalFilterEntriesFunc m_AddRetrievalFilterEntriesFunc;

        public int GetRetrievalFilter(ref D3D10_INFO_QUEUE_FILTER pFilter, IntPtr pFilterByteLength)
        {
            if(m_GetRetrievalFilterFunc==null){
                var fp = GetFunctionPointer(21);
                m_GetRetrievalFilterFunc = (GetRetrievalFilterFunc)Marshal.GetDelegateForFunctionPointer(fp, typeof(GetRetrievalFilterFunc));
            } 
            return  m_GetRetrievalFilterFunc(m_ptr, ref pFilter, pFilterByteLength);
        }
        delegate int GetRetrievalFilterFunc(IntPtr self, ref D3D10_INFO_QUEUE_FILTER pFilter, IntPtr pFilterByteLength);
        GetRetrievalFilterFunc m_GetRetrievalFilterFunc;

        public void ClearRetrievalFilter()
        {
            if(m_ClearRetrievalFilterFunc==null){
                var fp = GetFunctionPointer(22);
                m_ClearRetrievalFilterFunc = (ClearRetrievalFilterFunc)Marshal.GetDelegateForFunctionPointer(fp, typeof(ClearRetrievalFilterFunc));
            } 
             m_ClearRetrievalFilterFunc(m_ptr);
        }
        delegate void ClearRetrievalFilterFunc(IntPtr self);
        ClearRetrievalFilterFunc m_ClearRetrievalFilterFunc;

        public int PushEmptyRetrievalFilter()
        {
            if(m_PushEmptyRetrievalFilterFunc==null){
                var fp = GetFunctionPointer(23);
                m_PushEmptyRetrievalFilterFunc = (PushEmptyRetrievalFilterFunc)Marshal.GetDelegateForFunctionPointer(fp, typeof(PushEmptyRetrievalFilterFunc));
            } 
            return  m_PushEmptyRetrievalFilterFunc(m_ptr);
        }
        delegate int PushEmptyRetrievalFilterFunc(IntPtr self);
        PushEmptyRetrievalFilterFunc m_PushEmptyRetrievalFilterFunc;

        public int PushCopyOfRetrievalFilter()
        {
            if(m_PushCopyOfRetrievalFilterFunc==null){
                var fp = GetFunctionPointer(24);
                m_PushCopyOfRetrievalFilterFunc = (PushCopyOfRetrievalFilterFunc)Marshal.GetDelegateForFunctionPointer(fp, typeof(PushCopyOfRetrievalFilterFunc));
            } 
            return  m_PushCopyOfRetrievalFilterFunc(m_ptr);
        }
        delegate int PushCopyOfRetrievalFilterFunc(IntPtr self);
        PushCopyOfRetrievalFilterFunc m_PushCopyOfRetrievalFilterFunc;

        public int PushRetrievalFilter(ref D3D10_INFO_QUEUE_FILTER pFilter)
        {
            if(m_PushRetrievalFilterFunc==null){
                var fp = GetFunctionPointer(25);
                m_PushRetrievalFilterFunc = (PushRetrievalFilterFunc)Marshal.GetDelegateForFunctionPointer(fp, typeof(PushRetrievalFilterFunc));
            } 
            return  m_PushRetrievalFilterFunc(m_ptr, ref pFilter);
        }
        delegate int PushRetrievalFilterFunc(IntPtr self, ref D3D10_INFO_QUEUE_FILTER pFilter);
        PushRetrievalFilterFunc m_PushRetrievalFilterFunc;

        public void PopRetrievalFilter()
        {
            if(m_PopRetrievalFilterFunc==null){
                var fp = GetFunctionPointer(26);
                m_PopRetrievalFilterFunc = (PopRetrievalFilterFunc)Marshal.GetDelegateForFunctionPointer(fp, typeof(PopRetrievalFilterFunc));
            } 
             m_PopRetrievalFilterFunc(m_ptr);
        }
        delegate void PopRetrievalFilterFunc(IntPtr self);
        PopRetrievalFilterFunc m_PopRetrievalFilterFunc;

        public uint GetRetrievalFilterStackSize()
        {
            if(m_GetRetrievalFilterStackSizeFunc==null){
                var fp = GetFunctionPointer(27);
                m_GetRetrievalFilterStackSizeFunc = (GetRetrievalFilterStackSizeFunc)Marshal.GetDelegateForFunctionPointer(fp, typeof(GetRetrievalFilterStackSizeFunc));
            } 
            return  m_GetRetrievalFilterStackSizeFunc(m_ptr);
        }
        delegate uint GetRetrievalFilterStackSizeFunc(IntPtr self);
        GetRetrievalFilterStackSizeFunc m_GetRetrievalFilterStackSizeFunc;

        public int AddMessage(D3D10_MESSAGE_CATEGORY Category, D3D10_MESSAGE_SEVERITY Severity, D3D10_MESSAGE_ID ID, [MarshalAs(UnmanagedType.LPStr)] string pDescription)
        {
            if(m_AddMessageFunc==null){
                var fp = GetFunctionPointer(28);
                m_AddMessageFunc = (AddMessageFunc)Marshal.GetDelegateForFunctionPointer(fp, typeof(AddMessageFunc));
            } 
            return  m_AddMessageFunc(m_ptr, Category, Severity, ID, pDescription);
        }
        delegate int AddMessageFunc(IntPtr self, D3D10_MESSAGE_CATEGORY Category, D3D10_MESSAGE_SEVERITY Severity, D3D10_MESSAGE_ID ID, [MarshalAs(UnmanagedType.LPStr)] string pDescription);
        AddMessageFunc m_AddMessageFunc;

        public int AddApplicationMessage(D3D10_MESSAGE_SEVERITY Severity, [MarshalAs(UnmanagedType.LPStr)] string pDescription)
        {
            if(m_AddApplicationMessageFunc==null){
                var fp = GetFunctionPointer(29);
                m_AddApplicationMessageFunc = (AddApplicationMessageFunc)Marshal.GetDelegateForFunctionPointer(fp, typeof(AddApplicationMessageFunc));
            } 
            return  m_AddApplicationMessageFunc(m_ptr, Severity, pDescription);
        }
        delegate int AddApplicationMessageFunc(IntPtr self, D3D10_MESSAGE_SEVERITY Severity, [MarshalAs(UnmanagedType.LPStr)] string pDescription);
        AddApplicationMessageFunc m_AddApplicationMessageFunc;

        public int SetBreakOnCategory(D3D10_MESSAGE_CATEGORY Category, int bEnable)
        {
            if(m_SetBreakOnCategoryFunc==null){
                var fp = GetFunctionPointer(30);
                m_SetBreakOnCategoryFunc = (SetBreakOnCategoryFunc)Marshal.GetDelegateForFunctionPointer(fp, typeof(SetBreakOnCategoryFunc));
            } 
            return  m_SetBreakOnCategoryFunc(m_ptr, Category, bEnable);
        }
        delegate int SetBreakOnCategoryFunc(IntPtr self, D3D10_MESSAGE_CATEGORY Category, int bEnable);
        SetBreakOnCategoryFunc m_SetBreakOnCategoryFunc;

        public int SetBreakOnSeverity(D3D10_MESSAGE_SEVERITY Severity, int bEnable)
        {
            if(m_SetBreakOnSeverityFunc==null){
                var fp = GetFunctionPointer(31);
                m_SetBreakOnSeverityFunc = (SetBreakOnSeverityFunc)Marshal.GetDelegateForFunctionPointer(fp, typeof(SetBreakOnSeverityFunc));
            } 
            return  m_SetBreakOnSeverityFunc(m_ptr, Severity, bEnable);
        }
        delegate int SetBreakOnSeverityFunc(IntPtr self, D3D10_MESSAGE_SEVERITY Severity, int bEnable);
        SetBreakOnSeverityFunc m_SetBreakOnSeverityFunc;

        public int SetBreakOnID(D3D10_MESSAGE_ID ID, int bEnable)
        {
            if(m_SetBreakOnIDFunc==null){
                var fp = GetFunctionPointer(32);
                m_SetBreakOnIDFunc = (SetBreakOnIDFunc)Marshal.GetDelegateForFunctionPointer(fp, typeof(SetBreakOnIDFunc));
            } 
            return  m_SetBreakOnIDFunc(m_ptr, ID, bEnable);
        }
        delegate int SetBreakOnIDFunc(IntPtr self, D3D10_MESSAGE_ID ID, int bEnable);
        SetBreakOnIDFunc m_SetBreakOnIDFunc;

        public int GetBreakOnCategory(D3D10_MESSAGE_CATEGORY Category)
        {
            if(m_GetBreakOnCategoryFunc==null){
                var fp = GetFunctionPointer(33);
                m_GetBreakOnCategoryFunc = (GetBreakOnCategoryFunc)Marshal.GetDelegateForFunctionPointer(fp, typeof(GetBreakOnCategoryFunc));
            } 
            return  m_GetBreakOnCategoryFunc(m_ptr, Category);
        }
        delegate int GetBreakOnCategoryFunc(IntPtr self, D3D10_MESSAGE_CATEGORY Category);
        GetBreakOnCategoryFunc m_GetBreakOnCategoryFunc;

        public int GetBreakOnSeverity(D3D10_MESSAGE_SEVERITY Severity)
        {
            if(m_GetBreakOnSeverityFunc==null){
                var fp = GetFunctionPointer(34);
                m_GetBreakOnSeverityFunc = (GetBreakOnSeverityFunc)Marshal.GetDelegateForFunctionPointer(fp, typeof(GetBreakOnSeverityFunc));
            } 
            return  m_GetBreakOnSeverityFunc(m_ptr, Severity);
        }
        delegate int GetBreakOnSeverityFunc(IntPtr self, D3D10_MESSAGE_SEVERITY Severity);
        GetBreakOnSeverityFunc m_GetBreakOnSeverityFunc;

        public int GetBreakOnID(D3D10_MESSAGE_ID ID)
        {
            if(m_GetBreakOnIDFunc==null){
                var fp = GetFunctionPointer(35);
                m_GetBreakOnIDFunc = (GetBreakOnIDFunc)Marshal.GetDelegateForFunctionPointer(fp, typeof(GetBreakOnIDFunc));
            } 
            return  m_GetBreakOnIDFunc(m_ptr, ID);
        }
        delegate int GetBreakOnIDFunc(IntPtr self, D3D10_MESSAGE_ID ID);
        GetBreakOnIDFunc m_GetBreakOnIDFunc;

        public void SetMuteDebugOutput(int bMute)
        {
            if(m_SetMuteDebugOutputFunc==null){
                var fp = GetFunctionPointer(36);
                m_SetMuteDebugOutputFunc = (SetMuteDebugOutputFunc)Marshal.GetDelegateForFunctionPointer(fp, typeof(SetMuteDebugOutputFunc));
            } 
             m_SetMuteDebugOutputFunc(m_ptr, bMute);
        }
        delegate void SetMuteDebugOutputFunc(IntPtr self, int bMute);
        SetMuteDebugOutputFunc m_SetMuteDebugOutputFunc;

        public int GetMuteDebugOutput()
        {
            if(m_GetMuteDebugOutputFunc==null){
                var fp = GetFunctionPointer(37);
                m_GetMuteDebugOutputFunc = (GetMuteDebugOutputFunc)Marshal.GetDelegateForFunctionPointer(fp, typeof(GetMuteDebugOutputFunc));
            } 
            return  m_GetMuteDebugOutputFunc(m_ptr);
        }
        delegate int GetMuteDebugOutputFunc(IntPtr self);
        GetMuteDebugOutputFunc m_GetMuteDebugOutputFunc;

    }
}
