// This source code was generated by ClangCaster
using System;
using System.Runtime.InteropServices;

namespace NWindowsKits
{
    // C:/Program Files (x86)/Windows Kits/10/Include/10.0.18362.0/um/urlmon.h:9426
    [StructLayout(LayoutKind.Sequential, CharSet = CharSet.Unicode)]
    public struct _tagCODEBASEHOLD // 2
    {
        public uint cbSize;
        public IntPtr szDistUnit;
        public IntPtr szCodeBase;
        public uint dwVersionMS;
        public uint dwVersionLS;
        public uint dwStyle;
    }
}
