// This source code was generated by ClangCaster
using System;
using System.Runtime.InteropServices;

namespace NWindowsKits
{
    // C:/Program Files (x86)/Windows Kits/10/Include/10.0.18362.0/um/urlmon.h:9616
    public class ICatalogFileInfo : IUnknown // 1
    {
        static Guid s_uuid = new Guid("711c7600-6b48-11d1-b403-00aa00b92af1");
        public static new ref Guid IID => ref s_uuid;
        public override ref Guid GetIID() { return ref s_uuid; }

        public int GetCatalogFile(ref IntPtr ppszCatalogFile)
        {
            if(m_GetCatalogFileFunc==null){
                var fp = GetFunctionPointer(3);
                m_GetCatalogFileFunc = (GetCatalogFileFunc)Marshal.GetDelegateForFunctionPointer(fp, typeof(GetCatalogFileFunc));
            } 
            
            return  m_GetCatalogFileFunc(m_ptr, ref ppszCatalogFile);
        }
        delegate int GetCatalogFileFunc(IntPtr self, ref IntPtr ppszCatalogFile);
        GetCatalogFileFunc m_GetCatalogFileFunc;

        public int GetJavaTrust(ref IntPtr ppJavaTrust)
        {
            if(m_GetJavaTrustFunc==null){
                var fp = GetFunctionPointer(4);
                m_GetJavaTrustFunc = (GetJavaTrustFunc)Marshal.GetDelegateForFunctionPointer(fp, typeof(GetJavaTrustFunc));
            } 
            
            return  m_GetJavaTrustFunc(m_ptr, ref ppJavaTrust);
        }
        delegate int GetJavaTrustFunc(IntPtr self, ref IntPtr ppJavaTrust);
        GetJavaTrustFunc m_GetJavaTrustFunc;

    }
}
