// This source code was generated by ClangCaster
using System;
using System.Runtime.InteropServices;

namespace NWindowsKits
{
    // C:/Program Files (x86)/Windows Kits/10/Include/10.0.18362.0/um/urlmon.h:10130
    public class IGetBindHandle : IUnknown // 1
    {
        static Guid s_uuid = new Guid("af0ff408-129d-4b20-91f0-02bd23d88352");
        public static new ref Guid IID => ref s_uuid;
        public override ref Guid GetIID() { return ref s_uuid; }

        public int GetBindHandle(BINDHANDLETYPES enumRequestedHandle, ref IntPtr pRetHandle)
        {
            if(m_GetBindHandleFunc==null){
                var fp = GetFunctionPointer(3);
                m_GetBindHandleFunc = (GetBindHandleFunc)Marshal.GetDelegateForFunctionPointer(fp, typeof(GetBindHandleFunc));
            } 
            
            return  m_GetBindHandleFunc(m_ptr, enumRequestedHandle, ref pRetHandle);
        }
        delegate int GetBindHandleFunc(IntPtr self, BINDHANDLETYPES enumRequestedHandle, ref IntPtr pRetHandle);
        GetBindHandleFunc m_GetBindHandleFunc;

    }
}
