// This source code was generated by ClangCaster
using System;
using System.Runtime.InteropServices;

namespace NWindowsKits
{
    // C:/Program Files (x86)/Windows Kits/10/Include/10.0.18362.0/um/urlmon.h:4084
    public class IHttpSecurity : IWindowForBindingUI
    {
        static Guid s_uuid = new Guid("79eac9d7-bafa-11ce-8c82-00aa004ba90b");
        public static new ref Guid IID => ref s_uuid;
        public override ref Guid GetIID() { return ref s_uuid; }

        public int OnSecurityProblem(uint dwProblem)
        {
            if(m_OnSecurityProblemFunc==null){
                var fp = GetFunctionPointer(4);
                m_OnSecurityProblemFunc = (OnSecurityProblemFunc)Marshal.GetDelegateForFunctionPointer(fp, typeof(OnSecurityProblemFunc));
            } 
            return  m_OnSecurityProblemFunc(m_ptr, dwProblem);
        }
        delegate int OnSecurityProblemFunc(IntPtr self, uint dwProblem);
        OnSecurityProblemFunc m_OnSecurityProblemFunc;

    }
}
