// This source code was generated by ClangCaster
using System;
using System.Runtime.InteropServices;

namespace NWindowsKits
{
    // C:/Program Files (x86)/Windows Kits/10/Include/10.0.18362.0/um/urlmon.h:2200
    public class IHttpNegotiate : IUnknown // 1
    {
        static Guid s_uuid = new Guid("79eac9d2-baf9-11ce-8c82-00aa004ba90b");
        public static new ref Guid IID => ref s_uuid;
        public override ref Guid GetIID() { return ref s_uuid; }

        public int BeginningTransaction([MarshalAs(UnmanagedType.LPWStr)] string szURL, [MarshalAs(UnmanagedType.LPWStr)] string szHeaders, uint dwReserved, ref IntPtr pszAdditionalHeaders)
        {
            if(m_BeginningTransactionFunc==null){
                var fp = GetFunctionPointer(3);
                m_BeginningTransactionFunc = (BeginningTransactionFunc)Marshal.GetDelegateForFunctionPointer(fp, typeof(BeginningTransactionFunc));
            } 
            
            return  m_BeginningTransactionFunc(m_ptr, szURL, szHeaders, dwReserved, ref pszAdditionalHeaders);
        }
        delegate int BeginningTransactionFunc(IntPtr self, [MarshalAs(UnmanagedType.LPWStr)] string szURL, [MarshalAs(UnmanagedType.LPWStr)] string szHeaders, uint dwReserved, ref IntPtr pszAdditionalHeaders);
        BeginningTransactionFunc m_BeginningTransactionFunc;

        public int OnResponse(uint dwResponseCode, [MarshalAs(UnmanagedType.LPWStr)] string szResponseHeaders, [MarshalAs(UnmanagedType.LPWStr)] string szRequestHeaders, ref IntPtr pszAdditionalRequestHeaders)
        {
            if(m_OnResponseFunc==null){
                var fp = GetFunctionPointer(4);
                m_OnResponseFunc = (OnResponseFunc)Marshal.GetDelegateForFunctionPointer(fp, typeof(OnResponseFunc));
            } 
            
            return  m_OnResponseFunc(m_ptr, dwResponseCode, szResponseHeaders, szRequestHeaders, ref pszAdditionalRequestHeaders);
        }
        delegate int OnResponseFunc(IntPtr self, uint dwResponseCode, [MarshalAs(UnmanagedType.LPWStr)] string szResponseHeaders, [MarshalAs(UnmanagedType.LPWStr)] string szRequestHeaders, ref IntPtr pszAdditionalRequestHeaders);
        OnResponseFunc m_OnResponseFunc;

    }
}
