// This source code was generated by ClangCaster
using System;
using System.Runtime.InteropServices;

namespace NWindowsKits
{
    // C:/Program Files (x86)/Windows Kits/10/Include/10.0.18362.0/um/urlmon.h:9143
    public class IInternetZoneManagerEx2 : IInternetZoneManagerEx // 1
    {
        static Guid s_uuid = new Guid("edc17559-dd5d-4846-8eef-8becba5a4abf");
        public static new ref Guid IID => ref s_uuid;
        public override ref Guid GetIID() { return ref s_uuid; }

        public int GetZoneAttributesEx(uint dwZone, ref ZONEATTRIBUTES pZoneAttributes, uint dwFlags)
        {
            if(m_GetZoneAttributesExFunc==null){
                var fp = GetFunctionPointer(17);
                m_GetZoneAttributesExFunc = (GetZoneAttributesExFunc)Marshal.GetDelegateForFunctionPointer(fp, typeof(GetZoneAttributesExFunc));
            } 
            return  m_GetZoneAttributesExFunc(m_ptr, dwZone, ref pZoneAttributes, dwFlags);
        }
        delegate int GetZoneAttributesExFunc(IntPtr self, uint dwZone, ref ZONEATTRIBUTES pZoneAttributes, uint dwFlags);
        GetZoneAttributesExFunc m_GetZoneAttributesExFunc;

        public int GetZoneSecurityState(uint dwZoneIndex, int fRespectPolicy, ref uint pdwState, ref int pfPolicyEncountered)
        {
            if(m_GetZoneSecurityStateFunc==null){
                var fp = GetFunctionPointer(18);
                m_GetZoneSecurityStateFunc = (GetZoneSecurityStateFunc)Marshal.GetDelegateForFunctionPointer(fp, typeof(GetZoneSecurityStateFunc));
            } 
            return  m_GetZoneSecurityStateFunc(m_ptr, dwZoneIndex, fRespectPolicy, ref pdwState, ref pfPolicyEncountered);
        }
        delegate int GetZoneSecurityStateFunc(IntPtr self, uint dwZoneIndex, int fRespectPolicy, ref uint pdwState, ref int pfPolicyEncountered);
        GetZoneSecurityStateFunc m_GetZoneSecurityStateFunc;

        public int GetIESecurityState(int fRespectPolicy, ref uint pdwState, ref int pfPolicyEncountered, int fNoCache)
        {
            if(m_GetIESecurityStateFunc==null){
                var fp = GetFunctionPointer(19);
                m_GetIESecurityStateFunc = (GetIESecurityStateFunc)Marshal.GetDelegateForFunctionPointer(fp, typeof(GetIESecurityStateFunc));
            } 
            return  m_GetIESecurityStateFunc(m_ptr, fRespectPolicy, ref pdwState, ref pfPolicyEncountered, fNoCache);
        }
        delegate int GetIESecurityStateFunc(IntPtr self, int fRespectPolicy, ref uint pdwState, ref int pfPolicyEncountered, int fNoCache);
        GetIESecurityStateFunc m_GetIESecurityStateFunc;

        public int FixUnsecureSettings()
        {
            if(m_FixUnsecureSettingsFunc==null){
                var fp = GetFunctionPointer(20);
                m_FixUnsecureSettingsFunc = (FixUnsecureSettingsFunc)Marshal.GetDelegateForFunctionPointer(fp, typeof(FixUnsecureSettingsFunc));
            } 
            return  m_FixUnsecureSettingsFunc(m_ptr);
        }
        delegate int FixUnsecureSettingsFunc(IntPtr self);
        FixUnsecureSettingsFunc m_FixUnsecureSettingsFunc;

    }
}
