// This source code was generated by ClangCaster
using System;
using System.Runtime.InteropServices;

namespace NWindowsKits
{
    // C:/Program Files (x86)/Windows Kits/10/Include/10.0.18362.0/um/urlmon.h:7513
    public class IInternetSecurityManagerEx2 : IInternetSecurityManagerEx
    {
        static Guid s_uuid = new Guid("f1e50292-a795-4117-8e09-2b560a72ac60");
        public static new ref Guid IID => ref s_uuid;
        public override ref Guid GetIID() { return ref s_uuid; }

        public int MapUrlToZoneEx2(IntPtr pUri, ref uint pdwZone, uint dwFlags, ref IntPtr ppwszMappedUrl, ref uint pdwOutFlags)
        {
            if(m_MapUrlToZoneEx2Func==null){
                var fp = GetFunctionPointer(12);
                m_MapUrlToZoneEx2Func = (MapUrlToZoneEx2Func)Marshal.GetDelegateForFunctionPointer(fp, typeof(MapUrlToZoneEx2Func));
            } 
            return  m_MapUrlToZoneEx2Func(m_ptr, pUri, ref pdwZone, dwFlags, ref ppwszMappedUrl, ref pdwOutFlags);
        }
        delegate int MapUrlToZoneEx2Func(IntPtr self, IntPtr pUri, ref uint pdwZone, uint dwFlags, ref IntPtr ppwszMappedUrl, ref uint pdwOutFlags);
        MapUrlToZoneEx2Func m_MapUrlToZoneEx2Func;

        public int ProcessUrlActionEx2(IntPtr pUri, uint dwAction, ref byte pPolicy, uint cbPolicy, ref byte pContext, uint cbContext, uint dwFlags, ulong dwReserved, ref uint pdwOutFlags)
        {
            if(m_ProcessUrlActionEx2Func==null){
                var fp = GetFunctionPointer(13);
                m_ProcessUrlActionEx2Func = (ProcessUrlActionEx2Func)Marshal.GetDelegateForFunctionPointer(fp, typeof(ProcessUrlActionEx2Func));
            } 
            return  m_ProcessUrlActionEx2Func(m_ptr, pUri, dwAction, ref pPolicy, cbPolicy, ref pContext, cbContext, dwFlags, dwReserved, ref pdwOutFlags);
        }
        delegate int ProcessUrlActionEx2Func(IntPtr self, IntPtr pUri, uint dwAction, ref byte pPolicy, uint cbPolicy, ref byte pContext, uint cbContext, uint dwFlags, ulong dwReserved, ref uint pdwOutFlags);
        ProcessUrlActionEx2Func m_ProcessUrlActionEx2Func;

        public int GetSecurityIdEx2(IntPtr pUri, ref byte pbSecurityId, ref uint pcbSecurityId, ulong dwReserved)
        {
            if(m_GetSecurityIdEx2Func==null){
                var fp = GetFunctionPointer(14);
                m_GetSecurityIdEx2Func = (GetSecurityIdEx2Func)Marshal.GetDelegateForFunctionPointer(fp, typeof(GetSecurityIdEx2Func));
            } 
            return  m_GetSecurityIdEx2Func(m_ptr, pUri, ref pbSecurityId, ref pcbSecurityId, dwReserved);
        }
        delegate int GetSecurityIdEx2Func(IntPtr self, IntPtr pUri, ref byte pbSecurityId, ref uint pcbSecurityId, ulong dwReserved);
        GetSecurityIdEx2Func m_GetSecurityIdEx2Func;

        public int QueryCustomPolicyEx2(IntPtr pUri, ref GUID guidKey, ref IntPtr ppPolicy, ref uint pcbPolicy, ref byte pContext, uint cbContext, ulong dwReserved)
        {
            if(m_QueryCustomPolicyEx2Func==null){
                var fp = GetFunctionPointer(15);
                m_QueryCustomPolicyEx2Func = (QueryCustomPolicyEx2Func)Marshal.GetDelegateForFunctionPointer(fp, typeof(QueryCustomPolicyEx2Func));
            } 
            return  m_QueryCustomPolicyEx2Func(m_ptr, pUri, ref guidKey, ref ppPolicy, ref pcbPolicy, ref pContext, cbContext, dwReserved);
        }
        delegate int QueryCustomPolicyEx2Func(IntPtr self, IntPtr pUri, ref GUID guidKey, ref IntPtr ppPolicy, ref uint pcbPolicy, ref byte pContext, uint cbContext, ulong dwReserved);
        QueryCustomPolicyEx2Func m_QueryCustomPolicyEx2Func;

    }
}
