// This source code was generated by ClangCaster
using System;
using System.Runtime.InteropServices;

namespace NWindowsKits
{
    // C:/Program Files (x86)/Windows Kits/10/Include/10.0.18362.0/um/urlmon.h:4186
    public class IWinInetHttpInfo : IWinInetInfo // 1
    {
        static Guid s_uuid = new Guid("79eac9d8-bafa-11ce-8c82-00aa004ba90b");
        public static new ref Guid IID => ref s_uuid;
        public override ref Guid GetIID() { return ref s_uuid; }

        public int QueryInfo(uint dwOption, IntPtr pBuffer, ref uint pcbBuf, ref uint pdwFlags, ref uint pdwReserved)
        {
            if(m_QueryInfoFunc==null){
                var fp = GetFunctionPointer(4);
                m_QueryInfoFunc = (QueryInfoFunc)Marshal.GetDelegateForFunctionPointer(fp, typeof(QueryInfoFunc));
            } 
            
            return  m_QueryInfoFunc(m_ptr, dwOption, pBuffer, ref pcbBuf, ref pdwFlags, ref pdwReserved);
        }
        delegate int QueryInfoFunc(IntPtr self, uint dwOption, IntPtr pBuffer, ref uint pcbBuf, ref uint pdwFlags, ref uint pdwReserved);
        QueryInfoFunc m_QueryInfoFunc;

    }
}
