// This source code was generated by ClangCaster
using System;
using System.Runtime.InteropServices;

namespace NWindowsKits
{
    // C:/Program Files (x86)/Windows Kits/10/Include/10.0.18362.0/um/objidlbase.h:7336
    public class IProcessInitControl : IUnknown // 1
    {
        static Guid s_uuid = new Guid("72380d55-8d2b-43a3-8513-2b6ef31434e9");
        public static new ref Guid IID => ref s_uuid;
        public override ref Guid GetIID() { return ref s_uuid; }

        public int ResetInitializerTimeout(uint dwSecondsRemaining)
        {
            if(m_ResetInitializerTimeoutFunc==null){
                var fp = GetFunctionPointer(3);
                m_ResetInitializerTimeoutFunc = (ResetInitializerTimeoutFunc)Marshal.GetDelegateForFunctionPointer(fp, typeof(ResetInitializerTimeoutFunc));
            } 
            
            return  m_ResetInitializerTimeoutFunc(m_ptr, dwSecondsRemaining);
        }
        delegate int ResetInitializerTimeoutFunc(IntPtr self, uint dwSecondsRemaining);
        ResetInitializerTimeoutFunc m_ResetInitializerTimeoutFunc;

    }
}
