// This source code was generated by ClangCaster
using System;
using System.Runtime.InteropServices;

namespace NWindowsKits
{
    // C:/Program Files (x86)/Windows Kits/10/Include/10.0.18362.0/um/objidlbase.h:3548
    public class IPSFactoryBuffer : IUnknown // 1
    {
        static Guid s_uuid = new Guid("d5f569d0-593b-101a-b569-08002b2dbf7a");
        public static new ref Guid IID => ref s_uuid;
        public override ref Guid GetIID() { return ref s_uuid; }

        public int CreateProxy(IntPtr pUnkOuter, ref Guid riid, ref IntPtr ppProxy, ref IntPtr ppv)
        {
            if(m_CreateProxyFunc==null){
                var fp = GetFunctionPointer(3);
                m_CreateProxyFunc = (CreateProxyFunc)Marshal.GetDelegateForFunctionPointer(fp, typeof(CreateProxyFunc));
            } 
            
            return  m_CreateProxyFunc(m_ptr, pUnkOuter, ref riid, ref ppProxy, ref ppv);
        }
        delegate int CreateProxyFunc(IntPtr self, IntPtr pUnkOuter, ref Guid riid, ref IntPtr ppProxy, ref IntPtr ppv);
        CreateProxyFunc m_CreateProxyFunc;

        public int CreateStub(ref Guid riid, IntPtr pUnkServer, ref IntPtr ppStub)
        {
            if(m_CreateStubFunc==null){
                var fp = GetFunctionPointer(4);
                m_CreateStubFunc = (CreateStubFunc)Marshal.GetDelegateForFunctionPointer(fp, typeof(CreateStubFunc));
            } 
            
            return  m_CreateStubFunc(m_ptr, ref riid, pUnkServer, ref ppStub);
        }
        delegate int CreateStubFunc(IntPtr self, ref Guid riid, IntPtr pUnkServer, ref IntPtr ppStub);
        CreateStubFunc m_CreateStubFunc;

    }
}
