// This source code was generated by ClangCaster
using System;
using System.Runtime.InteropServices;

namespace NWindowsKits
{
    // C:/Program Files (x86)/Windows Kits/10/Include/10.0.18362.0/um/objidlbase.h:4928
    public class ISynchronizeHandle : IUnknown // 1
    {
        static Guid s_uuid = new Guid("00000031-0000-0000-c000-000000000046");
        public static new ref Guid IID => ref s_uuid;
        public override ref Guid GetIID() { return ref s_uuid; }

        public int GetHandle(ref IntPtr ph)
        {
            if(m_GetHandleFunc==null){
                var fp = GetFunctionPointer(3);
                m_GetHandleFunc = (GetHandleFunc)Marshal.GetDelegateForFunctionPointer(fp, typeof(GetHandleFunc));
            } 
            return  m_GetHandleFunc(m_ptr, ref ph);
        }
        delegate int GetHandleFunc(IntPtr self, ref IntPtr ph);
        GetHandleFunc m_GetHandleFunc;

    }
}
