// This source code was generated by ClangCaster
using System;
using System.Runtime.InteropServices;

namespace NWindowsKits
{
    // C:/Program Files (x86)/Windows Kits/10/Include/10.0.18362.0/um/d3d10_1.h:348
    public class ID3D10ShaderResourceView1 : ID3D10ShaderResourceView // 1
    {
        static Guid s_uuid = new Guid("9b7e4c87-342c-4106-a19f-4f2704f689f0");
        public static new ref Guid IID => ref s_uuid;
        public override ref Guid GetIID() { return ref s_uuid; }

        public void GetDesc1(ref D3D10_SHADER_RESOURCE_VIEW_DESC1 pDesc)
        {
            if(m_GetDesc1Func==null){
                var fp = GetFunctionPointer(9);
                m_GetDesc1Func = (GetDesc1Func)Marshal.GetDelegateForFunctionPointer(fp, typeof(GetDesc1Func));
            } 
            
             m_GetDesc1Func(m_ptr, ref pDesc);
        }
        delegate void GetDesc1Func(IntPtr self, ref D3D10_SHADER_RESOURCE_VIEW_DESC1 pDesc);
        GetDesc1Func m_GetDesc1Func;

    }
}
