// This source code was generated by ClangCaster
using System;
using System.Runtime.InteropServices;

namespace NWindowsKits
{
    // C:/Program Files (x86)/Windows Kits/10/Include/10.0.18362.0/um/ObjIdl.h:10825
    [StructLayout(LayoutKind.Sequential, CharSet = CharSet.Unicode)]
    public struct DVTARGETDEVICE
    {

        public uint tdSize;
        public ushort tdDriverNameOffset;
        public ushort tdDeviceNameOffset;
        public ushort tdPortNameOffset;
        public ushort tdExtDevmodeOffset;
        [MarshalAs(UnmanagedType.ByValArray, SizeConst = 1)] public byte[] tdData;
    }
}
