// This source code was generated by ClangCaster
using System;
using System.Runtime.InteropServices;

namespace NWindowsKits
{
    // C:/Program Files (x86)/Windows Kits/10/Include/10.0.18362.0/um/ObjIdl.h:11268
    [StructLayout(LayoutKind.Sequential, CharSet = CharSet.Unicode)]
    public struct uSTGMEDIUM // 1
    {
        public uint tymed;
        public __Anonymous__24 __field__1;
        public IntPtr pUnkForRelease;
    }
}
