// This source code was generated by ClangCaster
using System;
using System.Runtime.InteropServices;

namespace NWindowsKits
{
    // C:/Program Files (x86)/Windows Kits/10/Include/10.0.18362.0/shared/wtypes.h:705
    [StructLayout(LayoutKind.Explicit, CharSet = CharSet.Unicode)]
    public struct __Anonymous__37 // 1
    {

        [FieldOffset(0)] public __Anonymous__38 __field__0;

        [FieldOffset(0)] public ulong Lo64;
    }
}
