// This source code was generated by ClangCaster
using System;
using System.Runtime.InteropServices;

namespace NWindowsKits
{
    // C:/Program Files (x86)/Windows Kits/10/Include/10.0.18362.0/um/ObjIdl.h:11962
    public class AsyncIAdviseSink2 : AsyncIAdviseSink // 1
    {
        static Guid s_uuid = new Guid("00000151-0000-0000-c000-000000000046");
        public static new ref Guid IID => ref s_uuid;
        public override ref Guid GetIID() { return ref s_uuid; }

        public void Begin_OnLinkSrcChange(IntPtr pmk)
        {
            if(m_Begin_OnLinkSrcChangeFunc==null){
                var fp = GetFunctionPointer(13);
                m_Begin_OnLinkSrcChangeFunc = (Begin_OnLinkSrcChangeFunc)Marshal.GetDelegateForFunctionPointer(fp, typeof(Begin_OnLinkSrcChangeFunc));
            } 
             m_Begin_OnLinkSrcChangeFunc(m_ptr, pmk);
        }
        delegate void Begin_OnLinkSrcChangeFunc(IntPtr self, IntPtr pmk);
        Begin_OnLinkSrcChangeFunc m_Begin_OnLinkSrcChangeFunc;

        public void Finish_OnLinkSrcChange()
        {
            if(m_Finish_OnLinkSrcChangeFunc==null){
                var fp = GetFunctionPointer(14);
                m_Finish_OnLinkSrcChangeFunc = (Finish_OnLinkSrcChangeFunc)Marshal.GetDelegateForFunctionPointer(fp, typeof(Finish_OnLinkSrcChangeFunc));
            } 
             m_Finish_OnLinkSrcChangeFunc(m_ptr);
        }
        delegate void Finish_OnLinkSrcChangeFunc(IntPtr self);
        Finish_OnLinkSrcChangeFunc m_Finish_OnLinkSrcChangeFunc;

    }
}
