// This source code was generated by ClangCaster
using System;
using System.Runtime.InteropServices;

namespace NWindowsKits
{
    // C:/Program Files (x86)/Windows Kits/10/Include/10.0.18362.0/um/ObjIdl.h:14444
    public class IApartmentShutdown : IUnknown // 1
    {
        static Guid s_uuid = new Guid("a2f05a09-27a2-42b5-bc0e-ac163ef49d9b");
        public static new ref Guid IID => ref s_uuid;
        public override ref Guid GetIID() { return ref s_uuid; }

        public void OnUninitialize(ulong ui64ApartmentIdentifier)
        {
            if(m_OnUninitializeFunc==null){
                var fp = GetFunctionPointer(3);
                m_OnUninitializeFunc = (OnUninitializeFunc)Marshal.GetDelegateForFunctionPointer(fp, typeof(OnUninitializeFunc));
            } 
             m_OnUninitializeFunc(m_ptr, ui64ApartmentIdentifier);
        }
        delegate void OnUninitializeFunc(IntPtr self, ulong ui64ApartmentIdentifier);
        OnUninitializeFunc m_OnUninitializeFunc;

    }
}
