// This source code was generated by ClangCaster
using System;
using System.Runtime.InteropServices;

namespace NWindowsKits
{
    // C:/Program Files (x86)/Windows Kits/10/Include/10.0.18362.0/um/ObjIdl.h:12755
    public class IClassActivator : IUnknown // 1
    {
        static Guid s_uuid = new Guid("00000140-0000-0000-c000-000000000046");
        public static new ref Guid IID => ref s_uuid;
        public override ref Guid GetIID() { return ref s_uuid; }

        public int GetClassObject(ref Guid rclsid, uint dwClassContext, uint locale, ref Guid riid, ref IntPtr ppv)
        {
            if(m_GetClassObjectFunc==null){
                var fp = GetFunctionPointer(3);
                m_GetClassObjectFunc = (GetClassObjectFunc)Marshal.GetDelegateForFunctionPointer(fp, typeof(GetClassObjectFunc));
            } 
            
            return  m_GetClassObjectFunc(m_ptr, ref rclsid, dwClassContext, locale, ref riid, ref ppv);
        }
        delegate int GetClassObjectFunc(IntPtr self, ref Guid rclsid, uint dwClassContext, uint locale, ref Guid riid, ref IntPtr ppv);
        GetClassObjectFunc m_GetClassObjectFunc;

    }
}
