// This source code was generated by ClangCaster
using System;
using System.Runtime.InteropServices;

namespace NWindowsKits
{
    // C:/Program Files (x86)/Windows Kits/10/Include/10.0.18362.0/um/ObjIdl.h:13958
    public class IDummyHICONIncluder : IUnknown // 1
    {
        static Guid s_uuid = new Guid("947990de-cc28-11d2-a0f7-00805f858fb1");
        public static new ref Guid IID => ref s_uuid;
        public override ref Guid GetIID() { return ref s_uuid; }

        public int Dummy(HICON h1, HDC h2)
        {
            if(m_DummyFunc==null){
                var fp = GetFunctionPointer(3);
                m_DummyFunc = (DummyFunc)Marshal.GetDelegateForFunctionPointer(fp, typeof(DummyFunc));
            } 
            return  m_DummyFunc(m_ptr, h1, h2);
        }
        delegate int DummyFunc(IntPtr self, HICON h1, HDC h2);
        DummyFunc m_DummyFunc;

    }
}
