// This source code was generated by ClangCaster
using System;
using System.Runtime.InteropServices;

namespace NWindowsKits
{
    // C:/Program Files (x86)/Windows Kits/10/Include/10.0.18362.0/um/ObjIdl.h:13678
    public class IUrlMon : IUnknown
    {
        static Guid s_uuid = new Guid("00000026-0000-0000-c000-000000000046");
        public static new ref Guid IID => ref s_uuid;
        public override ref Guid GetIID() { return ref s_uuid; }

        public int AsyncGetClassBits(ref Guid rclsid, [MarshalAs(UnmanagedType.LPWStr)] string pszTYPE, [MarshalAs(UnmanagedType.LPWStr)] string pszExt, uint dwFileVersionMS, uint dwFileVersionLS, [MarshalAs(UnmanagedType.LPWStr)] string pszCodeBase, IntPtr pbc, uint dwClassContext, ref Guid riid, uint flags)
        {
            if(m_AsyncGetClassBitsFunc==null){
                var fp = GetFunctionPointer(3);
                m_AsyncGetClassBitsFunc = (AsyncGetClassBitsFunc)Marshal.GetDelegateForFunctionPointer(fp, typeof(AsyncGetClassBitsFunc));
            } 
            return  m_AsyncGetClassBitsFunc(m_ptr, ref rclsid, pszTYPE, pszExt, dwFileVersionMS, dwFileVersionLS, pszCodeBase, pbc, dwClassContext, ref riid, flags);
        }
        delegate int AsyncGetClassBitsFunc(IntPtr self, ref Guid rclsid, [MarshalAs(UnmanagedType.LPWStr)] string pszTYPE, [MarshalAs(UnmanagedType.LPWStr)] string pszExt, uint dwFileVersionMS, uint dwFileVersionLS, [MarshalAs(UnmanagedType.LPWStr)] string pszCodeBase, IntPtr pbc, uint dwClassContext, ref Guid riid, uint flags);
        AsyncGetClassBitsFunc m_AsyncGetClassBitsFunc;

    }
}
