// This source code was generated by ClangCaster
using System;
using System.Runtime.InteropServices;

namespace NWindowsKits
{
    // C:/Program Files (x86)/Windows Kits/10/Include/10.0.18362.0/shared/dxgi.h:1424
    public class IDXGIOutput : IDXGIObject // 1
    {
        static Guid s_uuid = new Guid("ae02eedb-c735-4690-8d52-5a8dc20213aa");
        public static new ref Guid IID => ref s_uuid;
        public override ref Guid GetIID() { return ref s_uuid; }

        public int GetDesc(ref DXGI_OUTPUT_DESC pDesc)
        {
            if(m_GetDescFunc==null){
                var fp = GetFunctionPointer(7);
                m_GetDescFunc = (GetDescFunc)Marshal.GetDelegateForFunctionPointer(fp, typeof(GetDescFunc));
            } 
            
            return  m_GetDescFunc(m_ptr, ref pDesc);
        }
        delegate int GetDescFunc(IntPtr self, ref DXGI_OUTPUT_DESC pDesc);
        GetDescFunc m_GetDescFunc;

        public int GetDisplayModeList(DXGI_FORMAT EnumFormat, uint Flags, ref uint pNumModes, ref DXGI_MODE_DESC pDesc)
        {
            if(m_GetDisplayModeListFunc==null){
                var fp = GetFunctionPointer(8);
                m_GetDisplayModeListFunc = (GetDisplayModeListFunc)Marshal.GetDelegateForFunctionPointer(fp, typeof(GetDisplayModeListFunc));
            } 
            
            return  m_GetDisplayModeListFunc(m_ptr, EnumFormat, Flags, ref pNumModes, ref pDesc);
        }
        delegate int GetDisplayModeListFunc(IntPtr self, DXGI_FORMAT EnumFormat, uint Flags, ref uint pNumModes, ref DXGI_MODE_DESC pDesc);
        GetDisplayModeListFunc m_GetDisplayModeListFunc;

        public int FindClosestMatchingMode(ref DXGI_MODE_DESC pModeToMatch, ref DXGI_MODE_DESC pClosestMatch, IntPtr pConcernedDevice)
        {
            if(m_FindClosestMatchingModeFunc==null){
                var fp = GetFunctionPointer(9);
                m_FindClosestMatchingModeFunc = (FindClosestMatchingModeFunc)Marshal.GetDelegateForFunctionPointer(fp, typeof(FindClosestMatchingModeFunc));
            } 
            
            return  m_FindClosestMatchingModeFunc(m_ptr, ref pModeToMatch, ref pClosestMatch, pConcernedDevice);
        }
        delegate int FindClosestMatchingModeFunc(IntPtr self, ref DXGI_MODE_DESC pModeToMatch, ref DXGI_MODE_DESC pClosestMatch, IntPtr pConcernedDevice);
        FindClosestMatchingModeFunc m_FindClosestMatchingModeFunc;

        public int WaitForVBlank()
        {
            if(m_WaitForVBlankFunc==null){
                var fp = GetFunctionPointer(10);
                m_WaitForVBlankFunc = (WaitForVBlankFunc)Marshal.GetDelegateForFunctionPointer(fp, typeof(WaitForVBlankFunc));
            } 
            
            return  m_WaitForVBlankFunc(m_ptr);
        }
        delegate int WaitForVBlankFunc(IntPtr self);
        WaitForVBlankFunc m_WaitForVBlankFunc;

        public int TakeOwnership(IntPtr pDevice, int Exclusive)
        {
            if(m_TakeOwnershipFunc==null){
                var fp = GetFunctionPointer(11);
                m_TakeOwnershipFunc = (TakeOwnershipFunc)Marshal.GetDelegateForFunctionPointer(fp, typeof(TakeOwnershipFunc));
            } 
            
            return  m_TakeOwnershipFunc(m_ptr, pDevice, Exclusive);
        }
        delegate int TakeOwnershipFunc(IntPtr self, IntPtr pDevice, int Exclusive);
        TakeOwnershipFunc m_TakeOwnershipFunc;

        public void ReleaseOwnership()
        {
            if(m_ReleaseOwnershipFunc==null){
                var fp = GetFunctionPointer(12);
                m_ReleaseOwnershipFunc = (ReleaseOwnershipFunc)Marshal.GetDelegateForFunctionPointer(fp, typeof(ReleaseOwnershipFunc));
            } 
            
             m_ReleaseOwnershipFunc(m_ptr);
        }
        delegate void ReleaseOwnershipFunc(IntPtr self);
        ReleaseOwnershipFunc m_ReleaseOwnershipFunc;

        public int GetGammaControlCapabilities(ref DXGI_GAMMA_CONTROL_CAPABILITIES pGammaCaps)
        {
            if(m_GetGammaControlCapabilitiesFunc==null){
                var fp = GetFunctionPointer(13);
                m_GetGammaControlCapabilitiesFunc = (GetGammaControlCapabilitiesFunc)Marshal.GetDelegateForFunctionPointer(fp, typeof(GetGammaControlCapabilitiesFunc));
            } 
            
            return  m_GetGammaControlCapabilitiesFunc(m_ptr, ref pGammaCaps);
        }
        delegate int GetGammaControlCapabilitiesFunc(IntPtr self, ref DXGI_GAMMA_CONTROL_CAPABILITIES pGammaCaps);
        GetGammaControlCapabilitiesFunc m_GetGammaControlCapabilitiesFunc;

        public int SetGammaControl(ref DXGI_GAMMA_CONTROL pArray)
        {
            if(m_SetGammaControlFunc==null){
                var fp = GetFunctionPointer(14);
                m_SetGammaControlFunc = (SetGammaControlFunc)Marshal.GetDelegateForFunctionPointer(fp, typeof(SetGammaControlFunc));
            } 
            
            return  m_SetGammaControlFunc(m_ptr, ref pArray);
        }
        delegate int SetGammaControlFunc(IntPtr self, ref DXGI_GAMMA_CONTROL pArray);
        SetGammaControlFunc m_SetGammaControlFunc;

        public int GetGammaControl(ref DXGI_GAMMA_CONTROL pArray)
        {
            if(m_GetGammaControlFunc==null){
                var fp = GetFunctionPointer(15);
                m_GetGammaControlFunc = (GetGammaControlFunc)Marshal.GetDelegateForFunctionPointer(fp, typeof(GetGammaControlFunc));
            } 
            
            return  m_GetGammaControlFunc(m_ptr, ref pArray);
        }
        delegate int GetGammaControlFunc(IntPtr self, ref DXGI_GAMMA_CONTROL pArray);
        GetGammaControlFunc m_GetGammaControlFunc;

        public int SetDisplaySurface(IntPtr pScanoutSurface)
        {
            if(m_SetDisplaySurfaceFunc==null){
                var fp = GetFunctionPointer(16);
                m_SetDisplaySurfaceFunc = (SetDisplaySurfaceFunc)Marshal.GetDelegateForFunctionPointer(fp, typeof(SetDisplaySurfaceFunc));
            } 
            
            return  m_SetDisplaySurfaceFunc(m_ptr, pScanoutSurface);
        }
        delegate int SetDisplaySurfaceFunc(IntPtr self, IntPtr pScanoutSurface);
        SetDisplaySurfaceFunc m_SetDisplaySurfaceFunc;

        public int GetDisplaySurfaceData(IntPtr pDestination)
        {
            if(m_GetDisplaySurfaceDataFunc==null){
                var fp = GetFunctionPointer(17);
                m_GetDisplaySurfaceDataFunc = (GetDisplaySurfaceDataFunc)Marshal.GetDelegateForFunctionPointer(fp, typeof(GetDisplaySurfaceDataFunc));
            } 
            
            return  m_GetDisplaySurfaceDataFunc(m_ptr, pDestination);
        }
        delegate int GetDisplaySurfaceDataFunc(IntPtr self, IntPtr pDestination);
        GetDisplaySurfaceDataFunc m_GetDisplaySurfaceDataFunc;

        public int GetFrameStatistics(ref DXGI_FRAME_STATISTICS pStats)
        {
            if(m_GetFrameStatisticsFunc==null){
                var fp = GetFunctionPointer(18);
                m_GetFrameStatisticsFunc = (GetFrameStatisticsFunc)Marshal.GetDelegateForFunctionPointer(fp, typeof(GetFrameStatisticsFunc));
            } 
            
            return  m_GetFrameStatisticsFunc(m_ptr, ref pStats);
        }
        delegate int GetFrameStatisticsFunc(IntPtr self, ref DXGI_FRAME_STATISTICS pStats);
        GetFrameStatisticsFunc m_GetFrameStatisticsFunc;

    }
}
