// This source code was generated by ClangCaster
using System;
using System.Runtime.InteropServices;

namespace NWindowsKits
{
    // C:/Program Files (x86)/Windows Kits/10/Include/10.0.18362.0/shared/dxgi.h:2596
    public class IDXGIAdapter1 : IDXGIAdapter // 1
    {
        static Guid s_uuid = new Guid("29038f61-3839-4626-91fd-086879011a05");
        public static new ref Guid IID => ref s_uuid;
        public override ref Guid GetIID() { return ref s_uuid; }

        public int GetDesc1(ref DXGI_ADAPTER_DESC1 pDesc)
        {
            if(m_GetDesc1Func==null){
                var fp = GetFunctionPointer(10);
                m_GetDesc1Func = (GetDesc1Func)Marshal.GetDelegateForFunctionPointer(fp, typeof(GetDesc1Func));
            } 
            
            return  m_GetDesc1Func(m_ptr, ref pDesc);
        }
        delegate int GetDesc1Func(IntPtr self, ref DXGI_ADAPTER_DESC1 pDesc);
        GetDesc1Func m_GetDesc1Func;

    }
}
