// This source code was generated by ClangCaster
using System;
using System.Runtime.InteropServices;

namespace NWindowsKits
{
    // C:/Program Files (x86)/Windows Kits/10/Include/10.0.18362.0/shared/dxgi.h:2185
    public class IDXGIDevice : IDXGIObject
    {
        static Guid s_uuid = new Guid("54ec77fa-1377-44e6-8c32-88fd5f44c84c");
        public static new ref Guid IID => ref s_uuid;
        public override ref Guid GetIID() { return ref s_uuid; }

        public int GetAdapter(ref IntPtr pAdapter)
        {
            if(m_GetAdapterFunc==null){
                var fp = GetFunctionPointer(7);
                m_GetAdapterFunc = (GetAdapterFunc)Marshal.GetDelegateForFunctionPointer(fp, typeof(GetAdapterFunc));
            } 
            return  m_GetAdapterFunc(m_ptr, ref pAdapter);
        }
        delegate int GetAdapterFunc(IntPtr self, ref IntPtr pAdapter);
        GetAdapterFunc m_GetAdapterFunc;

        public int CreateSurface(ref DXGI_SURFACE_DESC pDesc, uint NumSurfaces, uint Usage, ref DXGI_SHARED_RESOURCE pSharedResource, ref IntPtr ppSurface)
        {
            if(m_CreateSurfaceFunc==null){
                var fp = GetFunctionPointer(8);
                m_CreateSurfaceFunc = (CreateSurfaceFunc)Marshal.GetDelegateForFunctionPointer(fp, typeof(CreateSurfaceFunc));
            } 
            return  m_CreateSurfaceFunc(m_ptr, ref pDesc, NumSurfaces, Usage, ref pSharedResource, ref ppSurface);
        }
        delegate int CreateSurfaceFunc(IntPtr self, ref DXGI_SURFACE_DESC pDesc, uint NumSurfaces, uint Usage, ref DXGI_SHARED_RESOURCE pSharedResource, ref IntPtr ppSurface);
        CreateSurfaceFunc m_CreateSurfaceFunc;

        public int QueryResourceResidency(ref IntPtr ppResources, ref DXGI_RESIDENCY pResidencyStatus, uint NumResources)
        {
            if(m_QueryResourceResidencyFunc==null){
                var fp = GetFunctionPointer(9);
                m_QueryResourceResidencyFunc = (QueryResourceResidencyFunc)Marshal.GetDelegateForFunctionPointer(fp, typeof(QueryResourceResidencyFunc));
            } 
            return  m_QueryResourceResidencyFunc(m_ptr, ref ppResources, ref pResidencyStatus, NumResources);
        }
        delegate int QueryResourceResidencyFunc(IntPtr self, ref IntPtr ppResources, ref DXGI_RESIDENCY pResidencyStatus, uint NumResources);
        QueryResourceResidencyFunc m_QueryResourceResidencyFunc;

        public int SetGPUThreadPriority(int Priority)
        {
            if(m_SetGPUThreadPriorityFunc==null){
                var fp = GetFunctionPointer(10);
                m_SetGPUThreadPriorityFunc = (SetGPUThreadPriorityFunc)Marshal.GetDelegateForFunctionPointer(fp, typeof(SetGPUThreadPriorityFunc));
            } 
            return  m_SetGPUThreadPriorityFunc(m_ptr, Priority);
        }
        delegate int SetGPUThreadPriorityFunc(IntPtr self, int Priority);
        SetGPUThreadPriorityFunc m_SetGPUThreadPriorityFunc;

        public int GetGPUThreadPriority(ref int pPriority)
        {
            if(m_GetGPUThreadPriorityFunc==null){
                var fp = GetFunctionPointer(11);
                m_GetGPUThreadPriorityFunc = (GetGPUThreadPriorityFunc)Marshal.GetDelegateForFunctionPointer(fp, typeof(GetGPUThreadPriorityFunc));
            } 
            return  m_GetGPUThreadPriorityFunc(m_ptr, ref pPriority);
        }
        delegate int GetGPUThreadPriorityFunc(IntPtr self, ref int pPriority);
        GetGPUThreadPriorityFunc m_GetGPUThreadPriorityFunc;

    }
}
