// This source code was generated by ClangCaster
using System;
using System.Runtime.InteropServices;

namespace NWindowsKits
{
    // C:/Program Files (x86)/Windows Kits/10/Include/10.0.18362.0/shared/dxgitype.h:43
    [StructLayout(LayoutKind.Sequential)]
    public struct DXGI_GAMMA_CONTROL // 1
    {
        public DXGI_RGB Scale;
        public DXGI_RGB Offset;
        [MarshalAs(UnmanagedType.ByValArray, SizeConst = 1025)] public DXGI_RGB[] GammaCurve;
    }
}
