// This source code was generated by ClangCaster

namespace NWindowsKits
{
    // C:/Program Files (x86)/Windows Kits/10/include/10.0.18362.0/shared/dxgitype.h:74
    public enum DXGI_MODE_ROTATION // 1
    {
        _UNSPECIFIED = 0x0,
        _IDENTITY = 0x1,
        _ROTATE90 = 0x2,
        _ROTATE180 = 0x3,
        _ROTATE270 = 0x4,
    }
}
