// This source code was generated by ClangCaster
using System;
using System.Runtime.InteropServices;

namespace NWindowsKits
{
    // C:/Program Files (x86)/Windows Kits/10/Include/10.0.18362.0/um/propidlbase.h:295
    [StructLayout(LayoutKind.Explicit, CharSet = CharSet.Unicode)]
    public struct __Anonymous__26 // 1
    {

        [FieldOffset(0)] public __Anonymous__27 __field__0;

        [FieldOffset(0)] public DECIMAL decVal;
    }
}
