// This source code was generated by ClangCaster
using System;
using System.Runtime.InteropServices;

namespace NWindowsKits
{
    // C:/Program Files (x86)/Windows Kits/10/Include/10.0.18362.0/um/propidlbase.h:230
    [StructLayout(LayoutKind.Sequential, CharSet = CharSet.Unicode)]
    public struct CAH // 1
    {

        public uint cElems;
        public IntPtr pElems;
    }
}
