// This source code was generated by ClangCaster
using System;
using System.Runtime.InteropServices;

namespace NWindowsKits
{
    // C:/Program Files (x86)/Windows Kits/10/Include/10.0.18362.0/um/wingdi.h:2852
    [StructLayout(LayoutKind.Sequential, CharSet = CharSet.Unicode)]
    public struct __Anonymous__12 // 1
    {
        public uint videoStandard;
        public uint vSyncFreqDivider;
        public uint reserved;
    }
}
