// This source code was generated by ClangCaster
using System;
using System.Runtime.InteropServices;

namespace NWindowsKits
{
    // C:/Program Files (x86)/Windows Kits/10/Include/10.0.18362.0/um/wingdi.h:2946
    [StructLayout(LayoutKind.Sequential, CharSet = CharSet.Unicode)]
    public struct DISPLAYCONFIG_PATH_SOURCE_INFO // 1
    {
        // C:/Program Files (x86)/Windows Kits/10/Include/10.0.18362.0/um/wingdi.h:2950
        [StructLayout(LayoutKind.Explicit, CharSet = CharSet.Unicode)]
        public struct __Anonymous__0 // 0
        {
    
    
            [FieldOffset(0)] public uint modeInfoIdx;
    
            [FieldOffset(0)] public __Anonymous__1 __field__1;
        }
    
        // C:/Program Files (x86)/Windows Kits/10/Include/10.0.18362.0/um/wingdi.h:2953
        [StructLayout(LayoutKind.Sequential, CharSet = CharSet.Unicode)]
        public struct __Anonymous__1 // 0
        {
    
            public uint cloneGroupId;
            public uint sourceModeInfoIdx;
        }
    

        public LUID adapterId;
        public uint id;
        public __Anonymous__0 __field__2;
        public uint statusFlags;
    }
}
