// This source code was generated by ClangCaster

namespace NWindowsKits
{
    // C:/Program Files (x86)/Windows Kits/10/Include/10.0.18362.0/um/d3d11sdklayers.h:755
    public enum D3D11_MESSAGE_SEVERITY // 1
    {
        _CORRUPTION = 0x0,
        _ERROR = 0x1,
        _WARNING = 0x2,
        _INFO = 0x3,
        _MESSAGE = 0x4,
    }
}
