// This source code was generated by ClangCaster
using System;
using System.Runtime.InteropServices;

namespace NWindowsKits
{
    public static class MSG_
    {
       // C:/Program Files (x86)/Windows Kits/10/include/10.0.18362.0/um/winsock.h:543
       public const int OOB = 0x1;

       // C:/Program Files (x86)/Windows Kits/10/include/10.0.18362.0/um/winsock.h:544
       public const int PEEK = 0x2;

       // C:/Program Files (x86)/Windows Kits/10/include/10.0.18362.0/um/winsock.h:545
       public const int DONTROUTE = 0x4;

       // C:/Program Files (x86)/Windows Kits/10/include/10.0.18362.0/um/winsock.h:547
       public const int MAXIOVLEN = 16;

       // C:/Program Files (x86)/Windows Kits/10/include/10.0.18362.0/um/winsock.h:549
       public const int PARTIAL = 0x8000;

    }
}
