// This source code was generated by ClangCaster
using System;
using System.Runtime.InteropServices;

namespace NWindowsKits
{
    // C:/Program Files (x86)/Windows Kits/10/Include/10.0.18362.0/um/d3d11.h:3813
    [StructLayout(LayoutKind.Explicit, CharSet = CharSet.Unicode)]
    public struct __Anonymous__45 // 1
    {

        [FieldOffset(0)] public D3D11_BUFFER_RTV Buffer;

        [FieldOffset(0)] public D3D11_TEX1D_RTV Texture1D;

        [FieldOffset(0)] public D3D11_TEX1D_ARRAY_RTV Texture1DArray;

        [FieldOffset(0)] public D3D11_TEX2D_RTV Texture2D;

        [FieldOffset(0)] public D3D11_TEX2D_ARRAY_RTV Texture2DArray;

        [FieldOffset(0)] public D3D11_TEX2DMS_RTV Texture2DMS;

        [FieldOffset(0)] public D3D11_TEX2DMS_ARRAY_RTV Texture2DMSArray;

        [FieldOffset(0)] public D3D11_TEX3D_RTV Texture3D;
    }
}
