// This source code was generated by ClangCaster
using System;
using System.Runtime.InteropServices;

namespace NWindowsKits
{
    // C:/Program Files (x86)/Windows Kits/10/Include/10.0.18362.0/um/d3d11.h:11010
    [StructLayout(LayoutKind.Sequential, CharSet = CharSet.Unicode)]
    public struct D3D11_AUTHENTICATED_CONFIGURE_SHARED_RESOURCE_INPUT
    {

        public D3D11_AUTHENTICATED_CONFIGURE_INPUT Parameters;
        public D3D11_AUTHENTICATED_PROCESS_IDENTIFIER_TYPE ProcessType;
        public IntPtr ProcessHandle;
        public int AllowAccess;
    }
}
