// This source code was generated by ClangCaster
using System;
using System.Runtime.InteropServices;

namespace NWindowsKits
{
    // C:/Program Files (x86)/Windows Kits/10/Include/10.0.18362.0/um/d3d11.h:7319
    [StructLayout(LayoutKind.Sequential, CharSet = CharSet.Unicode)]
    public struct D3D11_FEATURE_DATA_FORMAT_SUPPORT2
    {

        public DXGI_FORMAT InFormat;
        public uint OutFormatSupport2;
    }
}
