// This source code was generated by ClangCaster
using System;
using System.Runtime.InteropServices;

namespace NWindowsKits
{
    // C:/Program Files (x86)/Windows Kits/10/Include/10.0.18362.0/um/d3d11.h:10891
    [StructLayout(LayoutKind.Sequential, CharSet = CharSet.Unicode)]
    public struct D3D11_AUTHENTICATED_QUERY_OUTPUT_ID_COUNT_INPUT
    {

        public D3D11_AUTHENTICATED_QUERY_INPUT Input;
        public IntPtr DeviceHandle;
        public IntPtr CryptoSessionHandle;
    }
}
