// This source code was generated by ClangCaster
using System;
using System.Runtime.InteropServices;

namespace NWindowsKits
{
    // C:/Program Files (x86)/Windows Kits/10/Include/10.0.18362.0/um/d3d11.h:10980
    [StructLayout(LayoutKind.Sequential, CharSet = CharSet.Unicode)]
    public struct D3D11_AUTHENTICATED_CONFIGURE_OUTPUT // 1
    {
        public D3D11_OMAC omac;
        public GUID ConfigureType;
        public IntPtr hChannel;
        public uint SequenceNumber;
        public int ReturnCode;
    }
}
