// This source code was generated by ClangCaster
using System;
using System.Runtime.InteropServices;

namespace NWindowsKits
{
    // C:/Program Files (x86)/Windows Kits/10/Include/10.0.18362.0/um/d3d11.h:10843
    [StructLayout(LayoutKind.Sequential, CharSet = CharSet.Unicode)]
    public struct D3D11_AUTHENTICATED_QUERY_CRYPTO_SESSION_INPUT // 1
    {
        public D3D11_AUTHENTICATED_QUERY_INPUT Input;
        public IntPtr DecoderHandle;
    }
}
