// This source code was generated by ClangCaster
using System;
using System.Runtime.InteropServices;

namespace NWindowsKits
{
    // C:/Program Files (x86)/Windows Kits/10/Include/10.0.18362.0/um/d3d11.h:3386
    [StructLayout(LayoutKind.Sequential, CharSet = CharSet.Unicode)]
    public struct D3D11_SHADER_RESOURCE_VIEW_DESC // 1
    {
        public DXGI_FORMAT Format;
        public D3D_SRV_DIMENSION ViewDimension;
        public __Anonymous__41 __field__2;
    }
}
