// This source code was generated by ClangCaster

namespace NWindowsKits
{
    // C:/Program Files (x86)/Windows Kits/10/Include/10.0.18362.0/um/d3d10.h:770
    public enum D3D10_MAP // 1
    {
        _READ = 0x1,
        _WRITE = 0x2,
        _READ_WRITE = 0x3,
        _WRITE_DISCARD = 0x4,
        _WRITE_NO_OVERWRITE = 0x5,
    }
}
