// This source code was generated by ClangCaster

namespace NWindowsKits
{
    // C:/Program Files (x86)/Windows Kits/10/Include/10.0.18362.0/um/d3d10.h:4614
    public enum D3D10_COUNTER
    {
        _GPU_IDLE = 0x0,
        _VERTEX_PROCESSING = 0x1,
        _GEOMETRY_PROCESSING = 0x2,
        _PIXEL_PROCESSING = 0x3,
        _OTHER_GPU_PROCESSING = 0x4,
        _HOST_ADAPTER_BANDWIDTH_UTILIZATION = 0x5,
        _LOCAL_VIDMEM_BANDWIDTH_UTILIZATION = 0x6,
        _VERTEX_THROUGHPUT_UTILIZATION = 0x7,
        _TRIANGLE_SETUP_THROUGHPUT_UTILIZATION = 0x8,
        _FILLRATE_THROUGHPUT_UTILIZATION = 0x9,
        _VS_MEMORY_LIMITED = 0xa,
        _VS_COMPUTATION_LIMITED = 0xb,
        _GS_MEMORY_LIMITED = 0xc,
        _GS_COMPUTATION_LIMITED = 0xd,
        _PS_MEMORY_LIMITED = 0xe,
        _PS_COMPUTATION_LIMITED = 0xf,
        _POST_TRANSFORM_CACHE_HIT_RATE = 0x10,
        _TEXTURE_CACHE_HIT_RATE = 0x11,
        _DEVICE_DEPENDENT_0 = 0x40000000,
    }
}
