// This source code was generated by ClangCaster

namespace NWindowsKits
{
    // C:/Program Files (x86)/Windows Kits/10/Include/10.0.18362.0/um/d3d10.h:4248
    public enum D3D10_QUERY
    {
        _EVENT = 0x0,
        _OCCLUSION = 0x1,
        _TIMESTAMP = 0x2,
        _TIMESTAMP_DISJOINT = 0x3,
        _PIPELINE_STATISTICS = 0x4,
        _OCCLUSION_PREDICATE = 0x5,
        _SO_STATISTICS = 0x6,
        _SO_OVERFLOW_PREDICATE = 0x7,
    }
}
