// This source code was generated by ClangCaster

namespace NWindowsKits
{
    // C:/Program Files (x86)/Windows Kits/10/Include/10.0.18362.0/um/d3d10.h:718
    public enum D3D10_RTV_DIMENSION // 1
    {
        _UNKNOWN = 0x0,
        _BUFFER = 0x1,
        _TEXTURE1D = 0x2,
        _TEXTURE1DARRAY = 0x3,
        _TEXTURE2D = 0x4,
        _TEXTURE2DARRAY = 0x5,
        _TEXTURE2DMS = 0x6,
        _TEXTURE2DMSARRAY = 0x7,
        _TEXTURE3D = 0x8,
    }
}
