// This source code was generated by ClangCaster
using System;
using System.Runtime.InteropServices;

namespace NWindowsKits
{
    // C:/Program Files (x86)/Windows Kits/10/Include/10.0.18362.0/um/winuser.h:4907
    [StructLayout(LayoutKind.Sequential)]
    public struct DLGTEMPLATE // 1
    {
        public uint style;
        public uint dwExtendedStyle;
        public ushort cdit;
        public short x;
        public short y;
        public short cx;
        public short cy;
    }
}
