// This source code was generated by ClangCaster
using System;
using System.Runtime.InteropServices;

namespace NWindowsKits
{
    // C:/Program Files (x86)/Windows Kits/10/Include/10.0.18362.0/um/winuser.h:15183
    [StructLayout(LayoutKind.Sequential)]
    public struct RAWINPUTDEVICE // 3
    {
        public ushort usUsagePage;
        public ushort usUsage;
        public uint dwFlags;
        public HWND hwndTarget;
    }
}
