// This source code was generated by ClangCaster
using System;
using System.Runtime.InteropServices;

namespace NWindowsKits
{
    // C:/Program Files (x86)/Windows Kits/10/Include/10.0.18362.0/um/winnt.h:863
    [StructLayout(LayoutKind.Sequential, CharSet = CharSet.Unicode)]
    public struct __Anonymous__22 // 1
    {
        public uint LowPart;
        public uint HighPart;
    }
}
