// This source code was generated by ClangCaster
using System;
using System.Runtime.InteropServices;

namespace NWindowsKits
{
    // C:/Program Files (x86)/Windows Kits/10/Include/10.0.18362.0/um/winnt.h:842
    [StructLayout(LayoutKind.Sequential)]
    public struct LARGE_INTEGER // 1
    {
        public __Anonymous__3 u;
        public long QuadPart;
    }
}
