// This source code was generated by ClangCaster
using System;
using System.Runtime.InteropServices;

namespace NWindowsKits
{
    // C:/Program Files (x86)/Windows Kits/10/Include/10.0.18362.0/um/oleidl.h:3821
    [StructLayout(LayoutKind.Sequential, CharSet = CharSet.Unicode)]
    public struct tagOLEVERB // 2
    {
        public int lVerb;
        public IntPtr lpszVerbName;
        public uint fuFlags;
        public uint grfAttribs;
    }
}
