// This source code was generated by ClangCaster
using System;
using System.Runtime.InteropServices;

namespace NWindowsKits
{
    // C:/Program Files (x86)/Windows Kits/10/Include/10.0.18362.0/shared/dxgi.h:169
    [StructLayout(LayoutKind.Sequential, CharSet = CharSet.Unicode)]
    public struct DXGI_FRAME_STATISTICS // 1
    {

        public uint PresentCount;
        public uint PresentRefreshCount;
        public uint SyncRefreshCount;
        public LARGE_INTEGER SyncQPCTime;
        public LARGE_INTEGER SyncGPUTime;
    }
}
