// This source code was generated by ClangCaster
using System;
using System.Runtime.InteropServices;

namespace NWindowsKits
{
    // C:/Program Files (x86)/Windows Kits/10/Include/10.0.18362.0/shared/dxgitype.h:23
    [StructLayout(LayoutKind.Sequential)]
    public struct DXGI_RGB // 1
    {
        public float Red;
        public float Green;
        public float Blue;
    }
}
