// This source code was generated by ClangCaster
using System;
using System.Runtime.InteropServices;

namespace NWindowsKits
{
    // C:/Program Files (x86)/Windows Kits/10/Include/10.0.18362.0/um/d3d10.h:1185
    [StructLayout(LayoutKind.Sequential, CharSet = CharSet.Unicode)]
    public struct D3D10_BLEND_DESC // 1
    {
        public int AlphaToCoverageEnable;
        [MarshalAs(UnmanagedType.ByValArray, SizeConst = 8)] public int[] BlendEnable;
        public D3D10_BLEND SrcBlend;
        public D3D10_BLEND DestBlend;
        public D3D10_BLEND_OP BlendOp;
        public D3D10_BLEND SrcBlendAlpha;
        public D3D10_BLEND DestBlendAlpha;
        public D3D10_BLEND_OP BlendOpAlpha;
        [MarshalAs(UnmanagedType.ByValArray, SizeConst = 8)] public byte[] RenderTargetWriteMask;
    }
}
