// This source code was generated by ClangCaster

namespace NWindowsKits
{
    public static partial class CW_
    {
        // C:/Program Files (x86)/Windows Kits/10/Include/10.0.18362.0/um/winuser.h:4403
        public const int _USEDEFAULT = unchecked((int)( ( int ) 0x80000000 ));

    }
}
