// This source code was generated by ClangCaster
using System;
using System.Runtime.InteropServices;

namespace NWindowsKits
{
    // C:/Program Files (x86)/Windows Kits/10/Include/10.0.18362.0/um/d3dcommon.h:453
    public delegate void PFN_DESTRUCTION_CALLBACK(
        IntPtr pData
    );

}
