// This source code was generated by ClangCaster
using System;
using System.Runtime.InteropServices;

namespace NWindowsKits
{
    // C:/Program Files (x86)/Windows Kits/10/Include/10.0.18362.0/um/OCIdl.h:1434
    [StructLayout(LayoutKind.Sequential, CharSet = CharSet.Unicode)]
    public struct CONTROLINFO // 2
    {
        public uint cb;
        public HACCEL hAccel;
        public ushort cAccel;
        public uint dwFlags;
    }
}
