// This source code was generated by ClangCaster
using System;
using System.Runtime.InteropServices;

namespace NWindowsKits
{
    // C:/Program Files (x86)/Windows Kits/10/Include/10.0.18362.0/um/OCIdl.h:6479
    [StructLayout(LayoutKind.Sequential, CharSet = CharSet.Unicode)]
    public struct QACONTAINER // 1
    {

        public uint cbSize;
        public IntPtr pClientSite;
        public IntPtr pAdviseSink;
        public IntPtr pPropertyNotifySink;
        public IntPtr pUnkEventSink;
        public uint dwAmbientFlags;
        public uint colorFore;
        public uint colorBack;
        public IntPtr pFont;
        public IntPtr pUndoMgr;
        public uint dwAppearance;
        public int lcid;
        public HPALETTE hpal;
        public IntPtr pBindHost;
        public IntPtr pOleControlSite;
        public IntPtr pServiceProvider;
    }
}
