// This source code was generated by ClangCaster
using System;
using System.Runtime.InteropServices;

namespace NWindowsKits
{
    // C:/Program Files (x86)/Windows Kits/10/Include/10.0.18362.0/um/OCIdl.h:3834
    public class IFontDisp : IDispatch // 1
    {
        static Guid s_uuid = new Guid("bef6e003-a874-101a-8bba-00aa00300cab");
        public static new ref Guid IID => ref s_uuid;
        public override ref Guid GetIID() { return ref s_uuid; }

    }
}
