// This source code was generated by ClangCaster
using System;
using System.Runtime.InteropServices;

namespace NWindowsKits
{
    // C:/Program Files (x86)/Windows Kits/10/Include/10.0.18362.0/um/OCIdl.h:6514
    public class IQuickActivate : IUnknown // 1
    {
        static Guid s_uuid = new Guid("cf51ed10-62fe-11cf-bf86-00a0c9034836");
        public static new ref Guid IID => ref s_uuid;
        public override ref Guid GetIID() { return ref s_uuid; }

        public int QuickActivate(ref QACONTAINER pQaContainer, ref QACONTROL pQaControl)
        {
            if(m_QuickActivateFunc==null){
                var fp = GetFunctionPointer(3);
                m_QuickActivateFunc = (QuickActivateFunc)Marshal.GetDelegateForFunctionPointer(fp, typeof(QuickActivateFunc));
            } 
            
            return  m_QuickActivateFunc(m_ptr, ref pQaContainer, ref pQaControl);
        }
        delegate int QuickActivateFunc(IntPtr self, ref QACONTAINER pQaContainer, ref QACONTROL pQaControl);
        QuickActivateFunc m_QuickActivateFunc;

        public int SetContentExtent(ref SIZE pSizel)
        {
            if(m_SetContentExtentFunc==null){
                var fp = GetFunctionPointer(4);
                m_SetContentExtentFunc = (SetContentExtentFunc)Marshal.GetDelegateForFunctionPointer(fp, typeof(SetContentExtentFunc));
            } 
            
            return  m_SetContentExtentFunc(m_ptr, ref pSizel);
        }
        delegate int SetContentExtentFunc(IntPtr self, ref SIZE pSizel);
        SetContentExtentFunc m_SetContentExtentFunc;

        public int GetContentExtent(ref SIZE pSizel)
        {
            if(m_GetContentExtentFunc==null){
                var fp = GetFunctionPointer(5);
                m_GetContentExtentFunc = (GetContentExtentFunc)Marshal.GetDelegateForFunctionPointer(fp, typeof(GetContentExtentFunc));
            } 
            
            return  m_GetContentExtentFunc(m_ptr, ref pSizel);
        }
        delegate int GetContentExtentFunc(IntPtr self, ref SIZE pSizel);
        GetContentExtentFunc m_GetContentExtentFunc;

    }
}
