// This source code was generated by ClangCaster
using System;
using System.Runtime.InteropServices;

namespace NWindowsKits
{
    // C:/Program Files (x86)/Windows Kits/10/Include/10.0.18362.0/um/OCIdl.h:2304
    public class ISpecifyPropertyPages : IUnknown // 1
    {
        static Guid s_uuid = new Guid("b196b28b-bab4-101a-b69c-00aa00341d07");
        public static new ref Guid IID => ref s_uuid;
        public override ref Guid GetIID() { return ref s_uuid; }

        public int GetPages(ref CAUUID pPages)
        {
            if(m_GetPagesFunc==null){
                var fp = GetFunctionPointer(3);
                m_GetPagesFunc = (GetPagesFunc)Marshal.GetDelegateForFunctionPointer(fp, typeof(GetPagesFunc));
            } 
            
            return  m_GetPagesFunc(m_ptr, ref pPages);
        }
        delegate int GetPagesFunc(IntPtr self, ref CAUUID pPages);
        GetPagesFunc m_GetPagesFunc;

    }
}
