// This source code was generated by ClangCaster

namespace NWindowsKits
{
    // C:/Program Files (x86)/Windows Kits/10/Include/10.0.18362.0/um/d3dcommon.h:864
    public enum D3D_RESOURCE_RETURN_TYPE
    {
        D3D_RETURN_TYPE_UNORM = 0x1,
        D3D_RETURN_TYPE_SNORM = 0x2,
        D3D_RETURN_TYPE_SINT = 0x3,
        D3D_RETURN_TYPE_UINT = 0x4,
        D3D_RETURN_TYPE_FLOAT = 0x5,
        D3D_RETURN_TYPE_MIXED = 0x6,
        D3D_RETURN_TYPE_DOUBLE = 0x7,
        D3D_RETURN_TYPE_CONTINUED = 0x8,
        D3D10_RETURN_TYPE_UNORM = 0x1,
        D3D10_RETURN_TYPE_SNORM = 0x2,
        D3D10_RETURN_TYPE_SINT = 0x3,
        D3D10_RETURN_TYPE_UINT = 0x4,
        D3D10_RETURN_TYPE_FLOAT = 0x5,
        D3D10_RETURN_TYPE_MIXED = 0x6,
        D3D11_RETURN_TYPE_UNORM = 0x1,
        D3D11_RETURN_TYPE_SNORM = 0x2,
        D3D11_RETURN_TYPE_SINT = 0x3,
        D3D11_RETURN_TYPE_UINT = 0x4,
        D3D11_RETURN_TYPE_FLOAT = 0x5,
        D3D11_RETURN_TYPE_MIXED = 0x6,
        D3D11_RETURN_TYPE_DOUBLE = 0x7,
        D3D11_RETURN_TYPE_CONTINUED = 0x8,
    }
}
