// This source code was generated by ClangCaster

namespace NWindowsKits
{
    // C:/Program Files (x86)/Windows Kits/10/Include/10.0.18362.0/um/d3dcommon.h:567
    public enum D3D_INCLUDE_TYPE // 1
    {
        D3D_INCLUDE_LOCAL = 0x0,
        D3D_INCLUDE_SYSTEM = 0x1,
        D3D10_INCLUDE_LOCAL = 0x0,
        D3D10_INCLUDE_SYSTEM = 0x1,
        D3D_INCLUDE_FORCE_DWORD = unchecked((int)0x7fffffff),
    }
}
