// This source code was generated by ClangCaster
using System;
using System.Runtime.InteropServices;

namespace NWindowsKits
{
    // C:/Program Files (x86)/Windows Kits/10/Include/10.0.18362.0/shared/dxgi.h:197
    [StructLayout(LayoutKind.Sequential)]
    public struct DXGI_ADAPTER_DESC // 1
    {
        [MarshalAs(UnmanagedType.ByValArray, SizeConst = 128)] public ushort[] Description;
        public uint VendorId;
        public uint DeviceId;
        public uint SubSysId;
        public uint Revision;
        public ulong DedicatedVideoMemory;
        public ulong DedicatedSystemMemory;
        public ulong SharedSystemMemory;
        public LUID AdapterLuid;
    }
}
