// This source code was generated by ClangCaster

namespace NWindowsKits
{
    // C:/Program Files (x86)/Windows Kits/10/Include/10.0.18362.0/um/msxml.h:388
    public enum DOMNodeType // 1
    {
        _INVALID = 0x0,
        _ELEMENT = 0x1,
        _ATTRIBUTE = 0x2,
        _TEXT = 0x3,
        _CDATA_SECTION = 0x4,
        _ENTITY_REFERENCE = 0x5,
        _ENTITY = 0x6,
        _PROCESSING_INSTRUCTION = 0x7,
        _COMMENT = 0x8,
        _DOCUMENT = 0x9,
        _DOCUMENT_TYPE = 0xa,
        _DOCUMENT_FRAGMENT = 0xb,
        _NOTATION = 0xc,
    }
}
