// This source code was generated by ClangCaster

namespace NWindowsKits
{
    // C:/Program Files (x86)/Windows Kits/10/Include/10.0.18362.0/shared/windef.h:252
    public enum DPI_AWARENESS
    {
        _INVALID = unchecked((int)0xffffffff),
        _UNAWARE = 0x0,
        _SYSTEM_AWARE = 0x1,
        _PER_MONITOR_AWARE = 0x2,
    }
}
