// This source code was generated by ClangCaster

namespace NWindowsKits
{
    // C:/Program Files (x86)/Windows Kits/10/Include/10.0.18362.0/shared/windef.h:265
    public enum DPI_HOSTING_BEHAVIOR // 1
    {
        _INVALID = unchecked((int)0xffffffff),
        _DEFAULT = 0x0,
        _MIXED = 0x1,
    }
}
