// This source code was generated by ClangCaster
using System;
using System.Runtime.InteropServices;

namespace NWindowsKits
{
    // C:/Program Files (x86)/Windows Kits/10/Include/10.0.18362.0/um/d3d10effect.h:883
    [StructLayout(LayoutKind.Sequential, CharSet = CharSet.Unicode)]
    public struct D3D10_EFFECT_SHADER_DESC // 1
    {

        public IntPtr pInputSignature;
        public int IsInline;
        public IntPtr pBytecode;
        public uint BytecodeLength;
        [MarshalAs(UnmanagedType.LPStr)] public string SODecl;
        public uint NumInputSignatureEntries;
        public uint NumOutputSignatureEntries;
    }
}
