// This source code was generated by ClangCaster
using System;
using System.Runtime.InteropServices;

namespace NWindowsKits
{
    // C:/Program Files (x86)/Windows Kits/10/Include/10.0.18362.0/um/d3d10effect.h:1190
    [StructLayout(LayoutKind.Sequential, CharSet = CharSet.Unicode)]
    public struct D3D10_PASS_SHADER_DESC // 1
    {

        public IntPtr pShaderVariable;
        public uint ShaderIndex;
    }
}
