// This source code was generated by ClangCaster

namespace NWindowsKits
{
    // C:/Program Files (x86)/Windows Kits/10/Include/10.0.18362.0/um/ObjIdl.h:14040
    public enum ShutdownType // 1
    {
        IdleShutdown = 0x0,
        ForcedShutdown = 0x1,
    }
}
