// This source code was generated by ClangCaster

namespace NWindowsKits
{
    public static partial class WM_
    {
        // C:/Program Files (x86)/Windows Kits/10/Include/10.0.18362.0/um/dde.h:37
        public const int _DDE_FIRST = unchecked((int)0x03E0);

        // C:/Program Files (x86)/Windows Kits/10/Include/10.0.18362.0/um/dde.h:38
        public const int _DDE_INITIATE = unchecked((int)( _DDE_FIRST ));

        // C:/Program Files (x86)/Windows Kits/10/Include/10.0.18362.0/um/dde.h:39
        public const int _DDE_TERMINATE = unchecked((int)( _DDE_FIRST + 1 ));

        // C:/Program Files (x86)/Windows Kits/10/Include/10.0.18362.0/um/dde.h:40
        public const int _DDE_ADVISE = unchecked((int)( _DDE_FIRST + 2 ));

        // C:/Program Files (x86)/Windows Kits/10/Include/10.0.18362.0/um/dde.h:41
        public const int _DDE_UNADVISE = unchecked((int)( _DDE_FIRST + 3 ));

        // C:/Program Files (x86)/Windows Kits/10/Include/10.0.18362.0/um/dde.h:42
        public const int _DDE_ACK = unchecked((int)( _DDE_FIRST + 4 ));

        // C:/Program Files (x86)/Windows Kits/10/Include/10.0.18362.0/um/dde.h:43
        public const int _DDE_DATA = unchecked((int)( _DDE_FIRST + 5 ));

        // C:/Program Files (x86)/Windows Kits/10/Include/10.0.18362.0/um/dde.h:44
        public const int _DDE_REQUEST = unchecked((int)( _DDE_FIRST + 6 ));

        // C:/Program Files (x86)/Windows Kits/10/Include/10.0.18362.0/um/dde.h:45
        public const int _DDE_POKE = unchecked((int)( _DDE_FIRST + 7 ));

        // C:/Program Files (x86)/Windows Kits/10/Include/10.0.18362.0/um/dde.h:46
        public const int _DDE_EXECUTE = unchecked((int)( _DDE_FIRST + 8 ));

        // C:/Program Files (x86)/Windows Kits/10/Include/10.0.18362.0/um/dde.h:47
        public const int _DDE_LAST = unchecked((int)( _DDE_FIRST + 8 ));

    }
}
