// This source code was generated by ClangCaster
using System;
using System.Runtime.InteropServices;

namespace NWindowsKits
{
    // C:/Program Files (x86)/Windows Kits/10/Include/10.0.18362.0/um/oleidl.h:908
    public class IOleContainer : IParseDisplayName // 1
    {
        static Guid s_uuid = new Guid("0000011b-0000-0000-c000-000000000046");
        public static new ref Guid IID => ref s_uuid;
        public override ref Guid GetIID() { return ref s_uuid; }

        public int EnumObjects(uint grfFlags, ref IntPtr ppenum)
        {
            if(m_EnumObjectsFunc==null){
                var fp = GetFunctionPointer(4);
                m_EnumObjectsFunc = (EnumObjectsFunc)Marshal.GetDelegateForFunctionPointer(fp, typeof(EnumObjectsFunc));
            } 
            return  m_EnumObjectsFunc(m_ptr, grfFlags, ref ppenum);
        }
        delegate int EnumObjectsFunc(IntPtr self, uint grfFlags, ref IntPtr ppenum);
        EnumObjectsFunc m_EnumObjectsFunc;

        public int LockContainer(int fLock)
        {
            if(m_LockContainerFunc==null){
                var fp = GetFunctionPointer(5);
                m_LockContainerFunc = (LockContainerFunc)Marshal.GetDelegateForFunctionPointer(fp, typeof(LockContainerFunc));
            } 
            return  m_LockContainerFunc(m_ptr, fLock);
        }
        delegate int LockContainerFunc(IntPtr self, int fLock);
        LockContainerFunc m_LockContainerFunc;

    }
}
