// This source code was generated by ClangCaster
using System;
using System.Runtime.InteropServices;

namespace NWindowsKits
{
    // C:/Program Files (x86)/Windows Kits/10/Include/10.0.18362.0/um/oleidl.h:820
    public class IParseDisplayName : IUnknown // 1
    {
        static Guid s_uuid = new Guid("0000011a-0000-0000-c000-000000000046");
        public static new ref Guid IID => ref s_uuid;
        public override ref Guid GetIID() { return ref s_uuid; }

        public int ParseDisplayName(IntPtr pbc, IntPtr pszDisplayName, IntPtr pchEaten, ref IntPtr ppmkOut)
        {
            if(m_ParseDisplayNameFunc==null){
                var fp = GetFunctionPointer(3);
                m_ParseDisplayNameFunc = (ParseDisplayNameFunc)Marshal.GetDelegateForFunctionPointer(fp, typeof(ParseDisplayNameFunc));
            } 
            
            return  m_ParseDisplayNameFunc(m_ptr, pbc, pszDisplayName, pchEaten, ref ppmkOut);
        }
        delegate int ParseDisplayNameFunc(IntPtr self, IntPtr pbc, IntPtr pszDisplayName, IntPtr pchEaten, ref IntPtr ppmkOut);
        ParseDisplayNameFunc m_ParseDisplayNameFunc;

    }
}
