// This source code was generated by ClangCaster
using System;
using System.Runtime.InteropServices;

namespace NWindowsKits
{
    // C:/Program Files (x86)/Windows Kits/10/Include/10.0.18362.0/um/OAIdl.h:4615
    public class ISupportErrorInfo : IUnknown
    {
        static Guid s_uuid = new Guid("df0b3d60-548f-101b-8e65-08002b2bd119");
        public static new ref Guid IID => ref s_uuid;
        public override ref Guid GetIID() { return ref s_uuid; }

        public int InterfaceSupportsErrorInfo(ref Guid riid)
        {
            if(m_InterfaceSupportsErrorInfoFunc==null){
                var fp = GetFunctionPointer(3);
                m_InterfaceSupportsErrorInfoFunc = (InterfaceSupportsErrorInfoFunc)Marshal.GetDelegateForFunctionPointer(fp, typeof(InterfaceSupportsErrorInfoFunc));
            } 
            return  m_InterfaceSupportsErrorInfoFunc(m_ptr, ref riid);
        }
        delegate int InterfaceSupportsErrorInfoFunc(IntPtr self, ref Guid riid);
        InterfaceSupportsErrorInfoFunc m_InterfaceSupportsErrorInfoFunc;

    }
}
