// This source code was generated by ClangCaster
using System;
using System.Runtime.InteropServices;

namespace NWindowsKits
{
    // C:/Program Files (x86)/Windows Kits/10/Include/10.0.18362.0/um/OAIdl.h:472
    [StructLayout(LayoutKind.Sequential, CharSet = CharSet.Unicode)]
    public struct __Anonymous__33 // 1
    {
        public ushort vt;
        public ushort wReserved1;
        public ushort wReserved2;
        public ushort wReserved3;
        public __Anonymous__34 __field__4;
    }
}
