// This source code was generated by ClangCaster
using System;
using System.Runtime.InteropServices;

namespace NWindowsKits
{
    // C:/Program Files (x86)/Windows Kits/10/Include/10.0.18362.0/um/OAIdl.h:3686
    [StructLayout(LayoutKind.Sequential, CharSet = CharSet.Unicode)]
    public struct TLIBATTR // 2
    {
        public GUID guid;
        public uint lcid;
        public SYSKIND syskind;
        public ushort wMajorVerNum;
        public ushort wMinorVerNum;
        public ushort wLibFlags;
    }
}
